// ===================================================================
// Every piece of text the player sees, in one place
// -------------------------------------------------------------------
//   G.T("key", { name: value })   the string for `key` in G.lang, with
//                                 {name} placeholders filled in
//   data-i18n="key"               static HTML text (data-i18n-html for text
//                                 with markup, data-i18n-aria for aria-label)
//   G.localizeData()              names and labels that live on game data
//                                 (levels, weapons, achievements, shop items,
//                                 rarity and weight labels) -- by id, so no
//                                 save data ever depends on the text
// The Thai meanings of the vocabulary are NOT here: they are the learning
// content and stay in js/data/words_*.js. To add a language, add a block
// beside `en` with the same keys and set G.lang; anything missing falls
// back to English.
// ===================================================================
window.G = window.G || {};
G.lang = "en";
G.STRINGS = {
  en: {
    // ---- main menu ----
    "menu.title": "VOCAB <span class=\"accent\">ZOMBIE</span>",
    "menu.subtitle": "IELTS Survival FPS",
    "menu.start": "Start Game",
    "menu.practice": "Practice Mode",
    "menu.daily": "Daily Challenge",
    "menu.endless": "Endless Mode",
    "menu.leaderboard": "Leaderboard",
    "menu.achievements": "Achievements",
    "menu.vocablog": "Word Log",
    "menu.weaponlog": "Armory",
    "menu.import": "Import Vocabulary",
    "menu.customvocab": "Custom Vocabulary",
    "menu.howto": "How to Play",
    "menu.tutorial": "Replay Tutorial",
    "menu.settings": "Settings",
    "menu.footer": "v0.1 · Made with Three.js",
    "common.back": "Back",
    "common.close": "Close",
    "common.mainMenu": "Main Menu",
    "common.loading": "Loading...",
    "common.level": "Level {n}",
    "common.levelNamed": "Level {n}: {name}",
    "common.unknown": "unknown",

    // ---- level select ----
    "levels.title": "Select Level",
    "levels.back": "Back to Main Menu",
    "levels.info": "{waves} waves · Difficulty {diff}x",
    "levels.best": "Best score: {score}",
    "levels.locked": "🔒 Clear the previous level to unlock",
    "level.1": "Abandoned School",
    "level.2": "Abandoned Hospital",
    "level.3": "Underground Bunker",
    "level.daily": "Daily Challenge",
    "level.endless": "Endless",

    // ---- how to play ----
    "howto.title": "How to Play",
    "howto.body": "<p>The top of the screen shows the <strong>Thai meaning</strong> of a word — find the zombie carrying the English word with that meaning and shoot it!</p>"
      + "<ul><li><b>WASD</b> move, <b>Mouse</b> look, <b>Left click</b> shoot, <b>Hold right click</b> aim (zoom)</li>"
      + "<li><b>R</b> reload, <b>E</b> use / pick up, <b>Shift</b> sprint (uses the blue stamina bar, which refills when you stop)</li>"
      + "<li><b>1</b> knife (unlimited melee), <b>2-5</b> switch guns (<b>6-7</b> with the Extra Weapon Slot perk), or the <b>mouse wheel</b></li>"
      + "<li><b>ESC</b> pause</li>"
      + "<li>Controller: <b>RT</b> shoot, <b>LT</b> aim, <b>A</b> jump, <b>X</b> reload, <b>Y</b> use, <b>LB / RB</b> switch guns, <b>Menu</b> pause</li>"
      + "<li>Right zombie = score + money / wrong zombie = you lose health and the rest speed up</li>"
      + "<li>Between waves the shop always sells Full Health and Full Ammo, plus four perks that change every wave</li>"
      + "<li>Twenty waves a level: waves 5, 10, 15 and 20 end with a boss. Watch the ground: every boss move is marked before it lands. Beat a boss, then answer its hard word</li>"
      + "<li>Answer a boss's word right to pick an <b>ability</b> from the honeycomb (four at most). Use them with <b>Q F C X</b>, the controller's <b>D-pad</b>, or their touch buttons. No ability hurts a zombie: you still have to shoot the right word</li>"
      + "<li>The school's 3rd floor: see its checklist in the pause menu. After the Wave 10 boss the game keeps a <b>checkpoint</b>: you can continue from Wave 11</li></ul>"
      + "<h3>Memory boxes, Daily Review and spelling</h3>"
      + "<ul><li>Every word you meet goes into a <b>memory box</b> (1-5). Right when it is due: up one box, and it comes back later (after 1, 3, 7, 14, then 30 days). Wrong: back to box 1. Past box 5 it is <b>Mastered</b></li>"
      + "<li>Boxes 4 and 5 need you to <b>produce</b> the word (spell it): shooting the right zombie takes a word to box 3 at most. An answer found with a hint, or with a perk or ability that shows it, moves nothing</li>"
      + "<li><b>Daily Review</b> (Training tab) brings back every word due today. One session a day keeps your streak; a day with nothing due does not break it</li>"
      + "<li><b>Spelling</b>: each zombie shows a Thai meaning over its head. On a keyboard, type its English word in the bar at the bottom and press <b>Enter</b>: letters all go into the bar, so walk with the <b>arrow keys</b>, and <b>Tab</b> gives a hint. On a touch screen, tap the letters in order; on a controller, the <b>D-pad</b> and <b>A</b></li>"
      + "<li><b>Spell to Reload</b> (Settings, Gameplay): a reload asks for one of the wave's words first. Right: a full magazine; wrong: half</li></ul>"
      + "<h3>English clues, listening and context</h3>"
      + "<ul><li><b>Paraphrase</b>: the box at the top gives an English definition (≈ similar meaning). New words show the Thai under it; later, <b>0</b> (or the Thai button) shows it, but then the answer does not move the word's box</li>"
      + "<li><b>Listening</b>: the zombies carry Thai meanings; listen and shoot the right one. <b>Dictation</b>: the zombies have no labels; aim at one to hear its word, then spell it. Hear it again: <b>9</b>, 🔊 or the controller's <b>View</b>. Settings: accent, speed, Play Once</li>"
      + "<li><b>Context</b>: a sentence with a gap; shoot the zombie with the word that fills it, in the right form (indicate, indication, indicative...)</li>"
      + "<li>The end-of-wave quiz, the boss's question and the vocabulary locks ask eight kinds of question: meanings both ways, definitions, gaps, collocations, paraphrases, listening and spelling. A wrong answer shows the word in a sentence</li>"
      + "<li>The <b>Word Log</b>: click a word for its vocabulary card. In story notes, the level's words are underlined: tap one to look it up</li></ul>",

    // ---- settings ----
    "settings.title": "Settings",
    "settings.controls": "Controls",
    "settings.controlMode": "Control mode",
    "settings.controlAuto": "Automatic",
    "settings.controlDesktop": "Desktop Controls",
    "settings.controlTouch": "Touch Controls",
    "settings.mouseSens": "Mouse sensitivity ({v})",
    "settings.touchLayout": "Touch controls (position / size / opacity / sensitivity)",
    "settings.touchLayoutBtn": "Customize Controls",
    "settings.keybinds": "Key Bindings",
    "settings.resetKeys": "Reset to Default",
    "settings.audio": "Audio",
    "settings.sfxVolume": "Sound effects (guns, zombies, footsteps) ({v}%)",
    "settings.musicVolume": "Music ({v}%)",
    "settings.ambientVolume": "Ambience ({v}%)",
    "settings.speechVolume": "Word pronunciation ({v}%)",
    "settings.speechMode": "Read words aloud automatically",
    "settings.speechAfter": "After a correct answer (recommended)",
    "settings.speechBefore": "As soon as a new word appears (easier)",
    "settings.speechOff": "Off",
    "settings.speechTest": "Test Pronunciation",
    "settings.performance": "Performance",
    "settings.fpsCap": "FPS Cap",
    "settings.unlimited": "Unlimited",
    "settings.showFps": "Show FPS counter",
    "settings.showDraws": "Show draw call count",
    "settings.quality": "Graphics quality",
    "settings.qVlow": "Very Low", "settings.qLow": "Low", "settings.qMedium": "Medium", "settings.qHigh": "High", "settings.qVhigh": "Very High",
    "settings.gameSpeed": "Game speed ({v}x)",
    "settings.accessibility": "Accessibility",
    "settings.fontSize": "Text size",
    "settings.fontSmall": "Small", "settings.fontMedium": "Medium", "settings.fontLarge": "Large",
    "settings.colorblind": "Colorblind mode (adds rarity icons)",
    "settings.headBob": "Camera bob while walking/running ({v}%)",
    "settings.headBobOff": "Turn off camera bob entirely (for motion sickness)",
    "settings.vocabulary": "Vocabulary",
    "settings.customVocab": "Your own words ({n} added)",
    "settings.customVocabBtn": "Custom Vocabulary",
    "settings.saveData": "Save Data",
    "settings.exportSave": "Export Save",
    "settings.importSave": "Import Save",
    "key.forward": "Forward", "key.back": "Back", "key.left": "Left", "key.right": "Right", "key.sprint": "Sprint", "key.jump": "Jump",
    "key.reload": "Reload", "key.interact": "Interact", "key.melee": "Knife", "key.slot2": "Weapon slot 2", "key.slot3": "Weapon slot 3",
    "key.slot4": "Weapon slot 4", "key.slot5": "Weapon slot 5", "key.slot6": "Weapon slot 6 (perk)", "key.slot7": "Weapon slot 7 (perk)",
    "key.pause": "Pause",
    "save.importFailed": "Import failed: {msg}",
    "save.importConfirm": "Importing will overwrite ALL of your current progress.\n\n"
      + "File to import (exported {when}):\n"
      + "  Levels unlocked {al} · Words with stats {aw} · Achievements {aa} · Guns found {ag}\n\n"
      + "Current progress that will be replaced:\n"
      + "  Levels unlocked {bl} · Words with stats {bw} · Achievements {ba} · Guns found {bg}\n\n"
      + "Import this save?",
    "save.importDone": "Save imported",
    "save.persistFailTitle": "Can't save progress",
    "save.persistFailText": "The browser won't store data (private mode?) — use Export Save to keep a copy",
    "save.errRead": "Couldn't read the file",
    "save.errJson": "This file isn't JSON",
    "save.errNotSave": "This file isn't a Vocab Zombie save",
    "save.errCorrupt": "The save data in this file is damaged",

    // ---- leaderboard / achievements ----
    "leaderboard.title": "Leaderboard",
    "leaderboard.daily": "Daily",
    "leaderboard.endless": "Endless",
    "leaderboard.empty": "No scores yet",
    "achievements.title": "Achievements",
    "achievements.unlocked": "🏅 Achievement unlocked!",
    "ach.streak50.name": "Word Scholar", "ach.streak50.desc": "Answer 50 words correctly in a row",
    "ach.secret_crate.name": "Golden Fortune", "ach.secret_crate.desc": "Open a Secret/Legendary weapon crate",
    "ach.no_hit_level.name": "Untouchable", "ach.no_hit_level.desc": "Clear a level without a zombie ever touching you",
    "ach.all_levels.name": "Zombie Conqueror", "ach.all_levels.desc": "Clear every level in the game",
    "ach.first_boss.name": "Boss Hunter", "ach.first_boss.desc": "Defeat your first boss",
    "ach.endless_10.name": "Iron Will", "ach.endless_10.desc": "Survive to wave 10 in Endless Mode",
    "ach.notes_level1.name": "Keeper of Stories", "ach.notes_level1.desc": "Collect all 20 story notes at the Abandoned School",
    "ach.notes_level2.name": "Case Notes", "ach.notes_level2.desc": "Collect all 20 story notes at the Abandoned Hospital",
    "ach.notes_level3.name": "Classified", "ach.notes_level3.desc": "Collect all 20 story notes in the Underground Bunker",

    // ---- word log ----
    "vocablog.title": "Word Log",
    "vocablog.unseen": "Not seen yet",
    "vocablog.right": "Right {n}",
    "vocablog.wrong": "Wrong {n}",
    "vocablog.hear": "Hear {word}",
    "vocablog.custom": "Yours",

    // ---- armory (weapon log) ----
    "weaponlog.title": "Armory",
    "weaponlog.wall": "🔒 Wall guns in this level ({n})",
    "weaponlog.box": "🎴 Mystery box (${cost} a try)",
    "weaponlog.locked": "Locked",
    "weaponlog.odds": "Drop chance: {p}",
    "weaponlog.damage": "Damage: {d}",
    "weaponlog.pellets": " x{n} pellets",
    "weaponlog.rate": "Fire rate: {r}/s",
    "weaponlog.mag": "Magazine: {n}",
    "weaponlog.dps": "Est. DPS: {n}",
    "weaponlog.price": "Price: ${p}",
    "weaponlog.listen": "🔊 Listen",
    "weapon.mode": "Mode: {m}",
    "weapon.weight": "Weight: {w} ({v})",
    "weapon.speedPenalty": "Speed -{p}%",
    "weapon.noPenalty": "No speed penalty",
    "weapon.reload": "Reload: {s}s",
    "weapon.recoil": "Recoil: {r}",
    "weapon.pierce": "pierces",
    "weapon.splash": "area blast",
    "fire.melee": "Melee",
    "fire.charge": "Charge",
    "fire.splash": "Explosive",
    "fire.pellets": "Buckshot x{n}",
    "fire.scope": "Sniper (scoped)",
    "fire.burst": "{n}-round burst",
    "fire.pierce": "Pierces {n}",
    "fire.pierceAll": "Pierces all",
    "fire.auto": "Automatic",
    "fire.semi": "Semi-auto",
    "weight.light": "Light", "weight.medium": "Medium", "weight.heavy": "Heavy", "weight.very_heavy": "Very heavy",
    "rarity.common": "COMMON", "rarity.uncommon": "UNCOMMON", "rarity.rare": "RARE", "rarity.epic": "EPIC", "rarity.secret": "SECRET",

    // ---- import vocabulary ----
    "import.title": "Import Vocabulary",
    "import.fileHint": "Upload a .csv or .txt file with one <code>english,Thai meaning</code> pair per line",
    "import.ocrHint": "Or take a photo of a vocabulary page (basic OCR — needs internet the first time to load the library):",
    "import.save": "Import Words",
    "import.dest": "Add these words to",
    "import.destPractice": "A practice set (Practice Mode only)",
    "import.destLevel": "{level} — the level's word list",
    "import.sumPractice": "Words in the new practice set: {n}.",
    "import.sumLevel": "Words added to {level}: {n}.",
    "import.sumDupes": "Left out as duplicates ({n}):",
    "import.sumInvalid": "Left out as unusable ({n}):",
    "import.whyDup": "already in {level}",
    "import.whyDupFile": "repeated in this file",
    "import.sumSame": "Added, with the same Thai meaning as another word in the level (the two are never on the field together): {words}",
    "import.sets": "Imported Word Sets",
    "import.more": "... and {n} more",
    "import.none": "No valid words found",
    "import.ocrLoading": "Loading the OCR library (may take a moment the first time)...",
    "import.ocrReading": "Reading text from the image...",
    "import.ocrDone": "Done — check and fix the words before saving",
    "import.ocrFailed": "OCR failed: {msg} — try a CSV file instead",
    "import.ocrNoLib": "Couldn't load the OCR library (needs internet) — use a CSV file instead",
    "import.saved": "Word set saved — you can use it in Practice Mode",
    "import.setRow": "{name} ({n} words)",
    "import.delete": "Delete",
    "import.empty": "No imported word sets yet",

    // ---- practice mode ----
    "practice.title": "Practice Mode",
    "practice.quit": "End Practice",
    "practice.choose": "Choose a word set to practise:",
    "practice.weak": "Words I often get wrong",
    "practice.start": "Start Practice",
    "practice.notEnough": "This word set doesn't have enough words to practise (needs at least 4 meanings)",
    "practice.done": "Practice complete! {c}/{n} correct",
    "practice.correct": "Correct!",
    "practice.wrong": "Wrong — the answer is \"{a}\"",

    // ---- results ----
    "result.gameOver": "GAME OVER",
    "result.victory": "VICTORY!",
    "result.retry": "Retry",
    "result.playAgain": "Play Again",
    "result.levelSelect": "Level Select",
    "result.score": "Score",
    "result.wave": "Wave reached",
    "result.correct": "Correct",
    "result.wrong": "Wrong",
    "result.money": "Money earned",
    "result.review": "Words to review",
    "result.wrongTimes": "wrong {n}×",
    "result.perfect": "Great job — no wrong answers!",
    "result.bosses": "Bosses defeated",
    "result.bossesNone": "No boss defeated this run",

    // ---- HUD ----
    "hud.shootMeaning": "Shoot the word meaning",
    "hud.hearAgain": "Hear the word again",
    "hud.boss": "Boss health",
    "hud.bossAim": "Boss! Aim for {w}",
    "hud.skipTutorial": "Skip tutorial",
    "hud.combo": "COMBO x{n}",
    "hud.comboSaved": "🛡️ COMBO SAVED x{n}",
    "hud.resume": "Click the screen to resume",
    "hud.interact": "Press {key} to interact",
    "hud.answerToUnlock": "Answer to unlock",
    "hud.waiting": "Waiting for zombies...",
    "hud.hintFirst": "  (starts with \"{c}\")",
    "hud.hintLen": "  (starts with \"{c}\", {n} letters)",
    "hud.levelWave": "{level} · Wave {wave}",
    "hud.overtime": " (overtime)",
    "hud.objectives": "Objectives {d}/{n}",
    "hud.zombies": "Zombies: {n}",
    "hud.ammoMelee": "∞",
    "hud.fps": "{n} FPS",
    "hud.draws": "{n} draw calls",
    "hud.tris": "{n}k tris",

    // ---- prompts ({key}: the interact key, E on touch, Y on a controller) ----
    "prompt.wordDoor": "Press {key} to try the door (answer a word)",
    "prompt.buttonDone": "Pressed",
    "prompt.button": "Press {key} to push the button",
    "prompt.crate": "Press {key} to open the crate",
    "prompt.trap": "Press {key} to disarm the trap (answer a word)",
    "prompt.hatch": "Press {key} to open the hatch (answer a word)",
    "prompt.doorClose": "Press {key} to close",
    "prompt.doorOpen": "Press {key} to open",
    "prompt.mystery": "Press {key} to roll a gun (${cost})",
    "prompt.notEnough": " - not enough money",
    "prompt.wallGun": "Press {key} to buy {name} (${price}{short}) · {weight}",
    "prompt.pickUp": "Press {key} to pick up {name}",
    "prompt.pickUpTimer": " ({s}s)",

    // ---- word challenges (doors, crates, traps, hatches) ----
    "challenge.crate": "Answer to unlock the crate",
    "challenge.door": "Answer to open the door",
    "challenge.trap": "Answer to disarm the trap",
    "challenge.hatch": "Answer to open the hatch",
    "challenge.boss": "The boss's last word",

    // ---- banners and messages during play ----
    "banner.unlocked": "Unlocked",
    "banner.objectivesLeft": "Objectives not complete!",
    "banner.objectivesLeftText": "Zombies will keep coming until every objective is done (see the HUD / pause screen)",
    "banner.noMoney": "Not enough money",
    "banner.noMoneyText": "Costs ${cost} · you have ${have}",
    "banner.upstairs": "2nd floor unlocked!",
    "banner.upstairsText": "{n} zombies down",
    "banner.explored": "All explored!",
    "banner.exploredText": "Entered {n} rooms",
    "banner.key": "Key found!",
    "banner.keyText": "{k} / {n} keys",
    "banner.allObjectives": "Objectives complete!",
    "banner.clearThisWave": "Clear this wave to finish the level",
    "banner.surviveAll": "Survive every wave to finish the level",
    "banner.secondLife": "Back on your feet — once per wave",
    "banner.bossCorrect": "Correct!",
    "banner.bossCorrectText": "The boss's word is yours",

    // ---- objectives ----
    "obj.title": "Level objectives ({d}/{n})",
    "obj.survive": "Survive all {n} waves",
    "obj.correct": "Answer at least {n} words correctly",
    "obj.accuracy": "Word accuracy of {p}% or better",
    "obj.explore": "Explore {n} rooms or places",
    "obj.keys": "Find the {n} hidden keys",
    "obj.boss": "Defeat all {n} bosses",
    "obj.notes": "Read {n} story notes",

    // ---- bosses (round 2): a name each, and "The <epithet>" -- the epithet
    // is a C1-C2 word from js/data/words_bosses.js, its Thai shown with it ----
    "boss.the": "The {w}",
    "boss.hpLabel": "{name}, {title}",
    "cine.wave": "Wave {n}",
    "cine.defeated": "Defeated",
    "boss.gravedigger.name": "Mortimer Grave",
    "boss.gravedigger.ability": "Grave Slam",
    "boss.gravedigger.desc": "Crouches, leaps high and slams down where you were standing. A red circle marks the spot before he lands.",
    "boss.gravedigger.counter": "Get out of the red circle before it fills. A hit takes over half your health, but never kills you from full health.",
    "boss.gravedigger.look": "A hunched gravedigger in a long coat and hat, dragging a rusty shovel and a lantern. One eye glows green; the other is sewn shut.",
    "boss.gravedigger.weak": "his head",
    "boss.eye.name": "Iris Glare",
    "boss.eye.ability": "Searing Gaze",
    "boss.eye.desc": "Locks a red dot onto your feet that hunts you at exactly walking speed while her eye charges, then burns a beam along it.",
    "boss.eye.counter": "Sprint the moment the dot appears: with any gun you are faster than it, and the lighter the gun the sooner you are clear. Walking only keeps it on you.",
    "boss.eye.look": "A giant floating eye with heavy lids, a torn robe and tendrils, circled by a ring of smaller eyes.",
    "boss.eye.weak": "the pupil",
    "boss.headmaster.name": "Headmaster Bellow",
    "boss.headmaster.ability": "Deafening Roar",
    "boss.headmaster.desc": "Draws a huge breath while a red ring spreads round him, then roars for four seconds. Inside the ring you take damage and move at half speed until the roar ends.",
    "boss.headmaster.counter": "Keep your distance, and be out of the ring before he finishes breathing in.",
    "boss.headmaster.look": "A barrel-chested headmaster in a black gown and mortarboard, with red-glowing spectacles, a thick moustache, a jaw that drops open and a heavy cane.",
    "boss.headmaster.weak": "his head",
    "boss.matron.name": "Matron Mildred",
    "boss.matron.ability": "Brood Call",
    "boss.matron.desc": "Raises her arms, purple marks glow on the ground around you, and zombies climb out of them.",
    "boss.matron.counter": "They are ordinary zombies: shoot the one whose word matches the meaning. Keep moving so they cannot surround you.",
    "boss.matron.look": "A tall, thin nurse with needle fingers, a stitched grin and a glowing sac on her belly where her brood grows.",
    "boss.matron.weak": "the glowing sac",
    "boss.coach.name": "Coach Brutus",
    "boss.coach.ability": "Bull Rush",
    "boss.coach.desc": "Paws the ground and blows his whistle while a red lane shows his path to the edge of the arena, then charges down it.",
    "boss.coach.counter": "Step out of the lane. When he misses he crashes into the energy wall and is stunned, taking 50% more damage while he flashes.",
    "boss.coach.look": "A huge bull of a coach in a horned helmet, shoulder pads and jersey number 13, with arms like tree trunks.",
    "boss.coach.weak": "his head",
    "boss.thorn.name": "Hedge Thornwood",
    "boss.thorn.ability": "Root Ripple",
    "boss.thorn.desc": "Stamps, and rings of thorns roll out across the ground one after another.",
    "boss.thorn.counter": "Jump each ring as it reaches you, or stay farther away than the rings travel. A ring that catches you holds your feet for a moment.",
    "boss.thorn.look": "A walking tree with root feet, branch arms, a crown of thorns and a glowing amber heart in its chest.",
    "boss.thorn.weak": "the amber heart",
    "boss.storm.name": "Crackwell",
    "boss.storm.ability": "Forked Fury",
    "boss.storm.desc": "Blue circles flicker on the ground around you, then lightning strikes each one, and a second, quicker volley follows.",
    "boss.storm.counter": "Leave the circles as soon as they appear, then watch for the second volley.",
    "boss.storm.look": "A gaunt figure wrapped in copper coils, with tesla rods on his back and a crackling core inside a glass dome.",
    "boss.storm.weak": "the glass dome",
    "boss.chemist.name": "Professor Vitriol",
    "boss.chemist.ability": "Acid Rain",
    "boss.chemist.desc": "Hurls flasks of acid where you are heading. Each lands in a green circle and leaves a pool that burns for six seconds.",
    "boss.chemist.counter": "Change direction when the flasks fly, and never stand in the pools.",
    "boss.chemist.look": "A hunched scientist in a stained lab coat and a gas mask with glowing green lenses, an acid tank on his back and a sprayer for an arm.",
    "boss.chemist.weak": "the tank on his back",
    "boss.void.name": "Warden Vex",
    "boss.void.ability": "Event Horizon",
    "boss.void.desc": "Opens a swirling hole that drags you towards it; its centre burns.",
    "boss.void.counter": "Walk or sprint away: the pull is slower than your walk. Never let it drag you into the middle.",
    "boss.void.look": "A floating hooded robe with nothing inside but two white eyes and a ring of purple light, trailing chains under a purple halo.",
    "boss.void.weak": "the void under the hood",
    "boss.examiner.name": "Examiner Quill",
    "boss.examiner.ability": "Trick Question",
    "boss.examiner.desc": "Bursts into papers and appears as several copies around you, all throwing paper blades. Only one of them is real.",
    "boss.examiner.counter": "The copies are faintly see-through with blue eyes; the real one has red eyes. One shot pops a copy. Step sideways to dodge the blades.",
    "boss.examiner.look": "A tall, thin figure in a suit whose head is an exam paper marked F, holding a giant red pen and a clipboard.",
    "boss.examiner.weak": "the paper face",
    // (new series, round 2) three phases, and each boss's two new moves
    "boss.phase": "Phase {n}",
    "boss.phaseText": "New move: {move}",
    "boss.move.ward.name": "Tombstone Ward",
    "boss.move.ward.desc": "Plants his shovel as tombstones rise around him, and grave-keepers climb out of green-marked graves. While the stones stand he takes only 15% damage.",
    "boss.move.ward.counter": "Shoot each grave-keeper by its word: every right kill breaks a tombstone. Break them all and he is stunned and takes 50% more damage. A wrong kill raises the keeper again.",
    "boss.move.ward.hint": "Shoot the grave-keepers by their words to break the ward!",
    "boss.move.ward.broken": "Ward broken! Hit him now!",
    "boss.move.graveyard.name": "Graveyard Shift",
    "boss.move.graveyard.desc": "Digs in, and the ground around you splits into squares. Every other square bursts, then the rest.",
    "boss.move.graveyard.counter": "Stand on a square that is not marked, then step onto one that has just burst before the next set goes off.",
    "boss.move.graveyard.hint": "Stand on an unmarked square, then switch!",
    "boss.move.orbs.name": "Watcher Orbs",
    "boss.move.orbs.desc": "The small eyes around her break away and float after you, bursting when they touch you.",
    "boss.move.orbs.counter": "One shot pops an orb. They are slower than your walk, so back away while you shoot them down.",
    "boss.move.orbs.hint": "Shoot the orbs down before they reach you!",
    "boss.move.mirror.name": "Mirror Gaze",
    "boss.move.mirror.desc": "Narrows her eye and glows gold: every bullet that hits her flies back at you. Then the eye opens wide.",
    "boss.move.mirror.counter": "Stop shooting while she glows gold. When the eye opens, shoot the pupil: it takes 2.5x damage.",
    "boss.move.mirror.hint": "She reflects bullets: hold your fire!",
    "boss.move.mirror.hint2": "Her eye is open: shoot the pupil now!",
    "boss.move.detention.name": "Detention",
    "boss.move.detention.desc": "Rings the bell and draws a chalk ring around you that slowly closes in. The line stings and holds you back.",
    "boss.move.detention.counter": "Walk out through the green gap before the ring closes. Anyone still inside is hit and held in detention.",
    "boss.move.detention.hint": "Get out through the green gap!",
    "boss.move.assembly.name": "School Assembly",
    "boss.move.assembly.desc": "Calls an assembly: the ground burns red everywhere except one green circle nearby. Then again, smaller, somewhere else.",
    "boss.move.assembly.counter": "Run into the green circle before its countdown ends, then find the next one. Sprint if it is far.",
    "boss.move.assembly.hint": "Get into the green circle!",
    "boss.move.needles.name": "Sedative Volley",
    "boss.move.needles.desc": "Fans out her needle fingers: purple lanes show where a volley of sedative needles will fly, twice or more.",
    "boss.move.needles.counter": "Stand between two lanes, or move out of the fan. A needle slows you down for a few seconds.",
    "boss.move.needles.hint": "Stand between the purple lanes!",
    "boss.move.eggs.name": "Brood Sacs",
    "boss.move.eggs.desc": "Her sac swells and she flings pulsing eggs around you. Each hatches into a fast zombie when its ring fills.",
    "boss.move.eggs.counter": "Shoot the eggs before they hatch. A few shots break one.",
    "boss.move.eggs.hint": "Shoot the eggs before they hatch!",
    "boss.move.ball.name": "Medicine Ball",
    "boss.move.ball.desc": "Hurls a huge medicine ball down a lane. It bounces off the arena walls, and each new lane is shown before it rolls.",
    "boss.move.ball.counter": "Step out of the orange lane each time, and watch for the bounce.",
    "boss.move.ball.hint": "Dodge the ball, then watch for the bounce!",
    "boss.move.line.name": "Offensive Line",
    "boss.move.line.desc": "Blows his whistle, and a wall of ghost linemen charges across the whole arena. Green lanes mark the gaps in it.",
    "boss.move.line.counter": "Stand in a green gap before the line reaches you.",
    "boss.move.line.hint": "Get into a green gap before the line hits!",
    "boss.move.bark.name": "Barkskin",
    "boss.move.bark.desc": "Thick bark grows over him: he takes only 30% damage and walks faster. Now and then his amber heart opens.",
    "boss.move.bark.counter": "Wait for the heart to glow and shoot it: while it is open it takes 2.5x damage, bark or not.",
    "boss.move.bark.hint": "Bark! Shoot the heart when it glows!",
    "boss.move.overgrowth.name": "Overgrowth",
    "boss.move.overgrowth.desc": "Plunges his arms into the ground: brown lines run out from him and burst into walls of thorns that stay for several seconds.",
    "boss.move.overgrowth.counter": "Step off the marked lines before they burst, and keep clear of the thorn walls: they sting and slow you.",
    "boss.move.overgrowth.hint": "Get off the brown lines!",
    "boss.move.pylons.name": "Tesla Pylons",
    "boss.move.pylons.desc": "Tesla pylons crash down around you on bolts of lightning. Arcs flicker between them, then crackle.",
    "boss.move.pylons.counter": "Shoot the pylons down, and never stand between two of them when the arcs flicker.",
    "boss.move.pylons.hint": "Shoot the pylons! Don't stand between them!",
    "boss.move.arcs.name": "Arc Barrage",
    "boss.move.arcs.desc": "A thin blue line follows you, turns white and locks, then a bolt fires down it. Again and again.",
    "boss.move.arcs.counter": "When the line turns white, step sideways off it.",
    "boss.move.arcs.hint": "Step off the line when it turns white!",
    "boss.move.spray.name": "Acid Sprayer",
    "boss.move.spray.desc": "Aims his sprayer and sweeps a cone of acid from one side to the other. The pale area shows where it will go.",
    "boss.move.spray.counter": "Get behind him or farther away than the cone reaches, or move to where the spray has already passed.",
    "boss.move.spray.hint": "Get out of the spray's path!",
    "boss.move.miasma.name": "Miasma",
    "boss.move.miasma.desc": "Throws a canister that pours out a cloud of poison gas. The cloud drifts after you, slower than a walk.",
    "boss.move.miasma.counter": "Keep away from the cloud, or shoot the canister in its middle to blow the gas away.",
    "boss.move.miasma.hint": "Keep away from the gas, or shoot its canister!",
    "boss.move.blackout.name": "Lights Out",
    "boss.move.blackout.desc": "The lights die. In the dark he appears behind you and strikes: a glowing wedge and a whisper give him away.",
    "boss.move.blackout.counter": "Listen for the whisper, turn, and step out of the purple wedge.",
    "boss.move.blackout.hint": "Lights out! He strikes from behind: watch the wedge!",
    "boss.move.chains.name": "Warden's Chains",
    "boss.move.chains.desc": "Casts a chain down a purple lane. If it catches you, it drags you towards him.",
    "boss.move.chains.counter": "Step out of the lane before the chain flies. Caught? Shoot the glowing link, or sprint away.",
    "boss.move.chains.hint": "Step out of the chain's lane!",
    "boss.move.chains.hint2": "Chained! Shoot the glowing link!",
    "boss.move.choice.name": "Multiple Choice",
    "boss.move.choice.desc": "Splits into four of himself, each holding a word, and asks for one meaning. Only the one holding the right word is real.",
    "boss.move.choice.counter": "Shoot the one holding the word for that meaning: he is stunned and takes 30% more damage. A wrong one bursts on you.",
    "boss.move.choice.hint": "Shoot the one holding the right word!",
    "boss.move.choice.prompt": "Which one is real? Shoot the word for: {th}",
    "boss.move.choice.right": "Correct: {w}! He is stunned!",
    "boss.move.stamp.name": "Fail Stamp",
    "boss.move.stamp.desc": "A giant F stamp hovers over where you stand, then slams down. Another follows, then another.",
    "boss.move.stamp.counter": "Keep moving: step out of the red square before the stamp comes down.",
    "boss.move.stamp.hint": "Keep moving! Out of the red square!",

    // ---- the Boss Codex ----
    "codex.title": "Boss Codex",
    "codex.summary": "{n} of {total} bosses met · {d} defeated",
    "codex.unknown": "???",
    "codex.notMet": "Not met yet",
    "codex.counter": "How to survive it",
    "codex.phase1": "Phase 1 · full health to 66%",
    "codex.phase2": "Phase 2 · 66% to 33%",
    "codex.phase3": "Phase 3 · below 33%: faster, and in combos",
    "codex.weak": "Weak spot: {w} (half as much damage again)",
    "codex.swipe": "Like every boss, it also swipes at anyone who stands too close: a red wedge on the ground warns you.",
    "codex.record": "Met {m}× · defeated {d}×",
    "codex.open": "Open {name}",

    // ---- shop ----
    "shop.title": "Shop",
    "shop.timer": "Next wave in {s}s",
    "shop.money": "Money: ",
    "shop.continue": "Ready",
    "shop.timerLabel": "Next wave in",
    "shop.noLimit": "No time limit · the next wave waits until you press Ready",
    "shop.bonus": "Wave {w} cleared · bonus +${b}",
    "shop.level": "Level: {s}/{m}",
    "shop.owned": "Owned",
    "shop.max": "MAX",
    "shop.buy": "Buy",
    "shop.essentials": "Always Available",
    "shop.perks": "Perks This Wave",
    "shop.armory": "Armory",
    "shop.perkLevel": "Lv {l}/{m}",
    "shop.nextLevel": "Next level:",
    "shop.full": "Already full",
    "shop.interest": "interest +${v}",
    "shopItem.heal": "Full Health",
    "shopItem.heal.desc": "Back to full health ({hp}/{max} now)",
    "shopItem.ammo_refill": "Full Ammo",
    "shopItem.ammo_refill.desc": "A full magazine and full reserve for every gun you carry",
    "shopItem.dmg_up": "Damage +15%",
    "shopItem.dmg_up.desc": "Your {w} hits 15% harder",
    "shopItem.firerate_up": "Fire Rate +10%",
    "shopItem.firerate_up.desc": "Your {w} fires 10% faster",
    "shopItem.mag_up": "Magazine +20%",
    "shopItem.mag_up.desc": "Your {w} holds 20% more rounds",
    "shopItem.unlock_shotgun": "Unlock Shotgun",
    "shopItem.unlock_shotgun.desc": "Into a free slot — or you choose which gun to swap first",
    "shopItem.unlock_smg": "Unlock SMG",
    "shopItem.unlock_smg.desc": "Into a free slot — or you choose which gun to swap first",
    "shopItem.unlock_rifle": "Unlock Rifle",
    "shopItem.unlock_rifle.desc": "Into a free slot — or you choose which gun to swap first",
    "shopItem.crate_common": "Weapon Crate",
    "shopItem.crate_common.desc": "A random gun from this level, any rarity",

    // ---- perks (js/perks.js): {a} and {b} are the figures for the level ----
    "perkCat.vocab": "Vocabulary", "perkCat.move": "Movement", "perkCat.shoot": "Shooting", "perkCat.survive": "Survival", "perkCat.money": "Economy",
    "perk.perk_hint.name": "Hint Reader",
    "perk.perk_hint.desc1": "The word prompt shows the first letter of the word to shoot.",
    "perk.perk_hint.desc2": "The word prompt shows the first letter of the word to shoot and how many letters it has.",
    "perk.focus_time.name": "Focus Time",
    "perk.focus_time.desc": "After every right answer, the zombies slow to a third of their speed for {a} seconds.",
    "perk.combo_shield.name": "Combo Shield",
    "perk.combo_shield.desc": "One wrong answer doesn't break your combo. The shield comes back after {a} more right answers.",
    "perk.word_bounty.name": "Big Word Bounty",
    "perk.word_bounty.desc": "Hard words (8+ letters, or ones you've missed before) pay {a}% more money.",
    "perk.extra_time.name": "Extra Time",
    "perk.extra_time.desc": "{a} more seconds to answer door, crate and trap questions, and for the word after a boss.",
    "perk.perk_speed.name": "Fleet Foot",
    "perk.perk_speed.desc": "You move {a}% faster.",
    "perk.second_wind.name": "Second Wind",
    "perk.second_wind.desc": "Stamina comes back twice as fast, and after running dry you can sprint again at 10% instead of 20%.",
    "perk.pack_mule.name": "Pack Mule",
    "perk.pack_mule.desc": "Heavy guns slow you down and tire you out only half as much.",
    "perk.adrenaline.name": "Adrenaline",
    "perk.adrenaline.desc": "Every kill gives you {a}% extra speed for 3 seconds.",
    "perk.quick_hands.name": "Quick Hands",
    "perk.quick_hands.desc": "You reload and switch weapons {a}% faster.",
    "perk.piercing_rounds.name": "Piercing Rounds",
    "perk.piercing_rounds.desc1": "Every bullet carries on through one more zombie.",
    "perk.piercing_rounds.desc2": "Every bullet carries on through two more zombies.",
    "perk.last_round.name": "Last Round",
    "perk.last_round.desc1": "The last round in every magazine does triple damage.",
    "perk.last_round.desc2": "The last two rounds in every magazine do triple damage.",
    "perk.marksman.name": "Marksman",
    "perk.marksman.desc": "Fully aimed shots do {a}% more damage, and shotgun spread is halved.",
    "perk.bloodthirst.name": "Bloodthirst",
    "perk.bloodthirst.desc": "Every kill heals {a} HP, and a kill with the right word heals {b}.",
    "perk.perk_armor.name": "Riot Gear",
    "perk.perk_armor.desc": "You take {a}% less damage from bites and traps.",
    "perk.second_life.name": "Second Life",
    "perk.second_life.desc": "Once per wave, a hit that would kill you leaves you on {a}% health and knocks nearby zombies back.",
    "perk.thorns.name": "Thorns",
    "perk.thorns.desc": "A zombie that bites you takes {a} damage and is thrown back (never a kill, so it can't cost you an answer).",
    "perk.extra_slot.name": "Extra Weapon Slot",
    "perk.extra_slot.desc1": "Carry one more gun: 5 in all, plus the knife.",
    "perk.extra_slot.desc2": "Carry two more guns: 6 in all, plus the knife.",
    "perk.interest.name": "Savings Account",
    "perk.interest.desc": "Each time the shop opens you earn {a}% of the money you walk in with (up to ${b}).",
    "perk.lucky_charm.name": "Lucky Charm",
    "perk.lucky_charm.desc1": "Weapon crates roll their rarity twice and keep the better result.",
    "perk.lucky_charm.desc2": "Weapon crates roll their rarity three times and keep the best result.",
    // (B) the short names under the perk icons in the pause menu
    "perk.perk_hint.short": "Hint", "perk.focus_time.short": "Focus", "perk.combo_shield.short": "Shield", "perk.word_bounty.short": "Bounty",
    "perk.extra_time.short": "Time+", "perk.perk_speed.short": "Speed", "perk.second_wind.short": "Wind", "perk.pack_mule.short": "Mule",
    "perk.adrenaline.short": "Rush", "perk.quick_hands.short": "Hands", "perk.piercing_rounds.short": "Pierce", "perk.last_round.short": "Last Rd",
    "perk.marksman.short": "Aim", "perk.bloodthirst.short": "Blood", "perk.perk_armor.short": "Armor", "perk.second_life.short": "2nd Life",
    "perk.thorns.short": "Thorns", "perk.extra_slot.short": "Slot+", "perk.interest.short": "Savings", "perk.lucky_charm.short": "Luck",

    // ---- Inventory Full (js/loadout.js) ----
    "inv.title": "Inventory Full",
    "inv.sub": "Choose a gun to swap out, or keep your loadout.",
    "inv.newGun": "NEW GUN",
    "inv.damage": "Damage",
    "inv.rate": "Fire rate",
    "inv.mag": "Magazine",
    "inv.weight": "Weight",
    "inv.held": "in hand",
    "inv.ammo": "Ammo {m} / {r}",
    "inv.replace": "Swap for the new gun",
    "inv.keep": "Keep Current Loadout",
    "inv.dropNote": "A gun you swap out is dropped at your feet — you have {s} seconds to pick it back up.",
    "inv.keepWall": "Keeping your loadout costs nothing.",
    "inv.keepBox": "If you keep your loadout, the new gun waits on the floor beside the box.",
    "inv.keepFloor": "If you keep your loadout, the new gun stays on the floor for later.",
    "inv.keepStays": "If you keep your loadout, it stays where it is.",

    // ---- Custom Vocabulary (js/customvocab.js) ----
    "cv.title": "Custom Vocabulary",
    "cv.intro": "Add your own words to a level. They join that level's word list the next time you start it, and they're kept in your save (Export Save included). A definition, synonyms or an example are optional — question types that need one skip words without it.",
    "cv.more": "More details (optional)",
    "cv.less": "Hide details",
    "cv.definition": "Definition in English",
    "cv.synonyms": "Synonyms (commas between)",
    "cv.collocations": "Collocations (commas between)",
    "cv.example": "Example sentence",
    "cv.topic": "Topic",
    "cv.topicNone": "No topic",
    "cv.has.definition": "definition",
    "cv.has.synonyms": "synonyms",
    "cv.has.example": "example",
    "cv.has.collocations": "collocations",
    "cv.has.topic": "topic",
    "cv.errDupFamily": "“{w}” is already in the game — it's part of the word family of “{family}” in {level}. Nothing was saved.",
    "topic.general_academic": "General Academic",
    "topic.education": "Education",
    "topic.society_culture": "Society & Culture",
    "topic.media_communication": "Media & Communication",
    "topic.health": "Health",
    "topic.science_research": "Science & Research",
    "topic.environment": "Environment",
    "topic.technology": "Technology",
    "topic.government_law": "Government & Law",
    "topic.crime_security": "Crime & Security",
    "topic.work_economy": "Work & Economy",
    "topic.urban_life_transport": "Urban Life & Transport",
    "cv.en": "English Word",
    "cv.th": "Thai Meaning",
    "cv.level": "Level",
    "cv.add": "Add Word",
    "cv.saveChanges": "Save Changes",
    "cv.cancel": "Cancel",
    "cv.import": "Import CSV…",
    "cv.edit": "Edit",
    "cv.delete": "Delete",
    "cv.confirmDelete": "Tap again to delete",
    "cv.empty": "No words added to {level} yet.",
    "cv.editing": "Editing “{w}” — change it and save, or cancel.",
    "cv.added": "Added “{w}” to {level}.",
    "cv.updated": "Saved “{w}” in {level}.",
    "cv.deleted": "Deleted “{w}”.",
    "cv.warnSame": "Heads-up: {others} has exactly the same Thai meaning in this level, so the two will never be on the field at the same time.",
    "cv.errEmpty": "Fill in both the English word and the Thai meaning.",
    "cv.errLong": "That's too long (32 letters for the English word, 80 characters for the meaning).",
    "cv.errLetters": "The English word can only use the letters A–Z (a hyphen, an apostrophe or a single space between words is fine).",
    "cv.errThai": "The meaning needs to be written in Thai.",
    "cv.errDup": "“{w}” is already in the game — it's one of the words in {level}. Nothing was saved.",
    "cv.errDupCustom": "“{w}” is already on your list for {level}. Nothing was saved.",
    "cv.errLevel": "Choose a level.",

    // ---- crate and mystery box ----
    "crate.ok": "OK",
    "crate.stats": "Damage: {d}<br>Fire rate: {r} rounds/s<br>Magazine: {m}<br>",
    "mystery.pick": "Pick 1 card",
    "mystery.pickSub": "One of them is a top-tier gun — try your luck",
    "mystery.take": "Take Gun",
    "mystery.reveal": "All cards revealed",
    "mystery.revealSub": "See what you missed",
    "mystery.yourPick": "← your pick",
    "mystery.dps": "DPS ~{n}",
    "mystery.elite": "  ★ ELITE",

    // ---- pause ----
    "pause.title": "Paused",
    "pause.resume": "Resume",
    "pause.tutorial": "Restart Tutorial",
    "pause.perks": "Perks",
    "pause.noPerks": "No perks yet — the shop sells four new ones between every wave.",
    "pause.perkHint": "Point at, tap or select a perk to see what it does.",

    // ---- tutorial ----
    "tut.move.title": "Move and look",
    "tut.move.desk": "Walk with W A S D · move the mouse to look · Shift to sprint · Space to jump",
    "tut.move.touch": "Drag the joystick (bottom left) to walk · drag on the right half of the screen to look · \"RUN\" to sprint",
    "tut.rule.title": "The main rule",
    "tut.rule.desk": "Read the Thai meaning at the top, then shoot the zombie carrying the matching English word — the wrong word costs health and speeds the zombies up",
    "tut.rule.touch": "Read the Thai meaning at the top, then shoot the zombie carrying the matching English word — the wrong word costs health and speeds the zombies up",
    "tut.shoot.title": "Shooting",
    "tut.shoot.desk": "Left click to shoot · hold right click to aim · R to reload · 1-5 to switch weapons · V to hear the word again",
    "tut.shoot.touch": "FIRE to shoot · AIM to zoom · R to reload · the number row switches weapons · 🔊 hears the word",
    "tut.door.title": "Doors",
    "tut.door.desk": "Press E to open or close a door — a closed door holds zombies back for a while",
    "tut.door.touch": "Press E to open or close a door — a closed door holds zombies back for a while",
    "tut.pickup.title": "Items",
    "tut.pickup.desk": "Walk over items to pick them up: money, ammo, health and weapon crates",
    "tut.pickup.touch": "Walk over items to pick them up: money, ammo, health and weapon crates",
    "tut.objectives.title": "Level goals",
    "tut.objectives.desk": "Surviving isn't enough — check \"Objectives x/6\" on the right, or press ESC for the full list (3 keys, rooms to explore, accuracy and the four bosses)",
    "tut.objectives.touch": "Surviving isn't enough — check \"Objectives x/6\" on the right, or press II for the full list (3 keys, rooms to explore, accuracy and the four bosses)",
    "tut.wallgun.title": "Wall guns",
    "tut.wallgun.desk": "Guns on the walls can be bought (press E when you have the money) — the heavier the gun, the slower you move and the faster you tire",
    "tut.wallgun.touch": "Guns on the walls can be bought (press E when you have the money) — the heavier the gun, the slower you move and the faster you tire",
    "tut.mystery.title": "Mystery box",
    "tut.mystery.desk": "$1,000 a try: pick 1 of 6 cards — one of them is always top tier",
    "tut.mystery.touch": "$1,000 a try: pick 1 of 6 cards — one of them is always top tier",
    "tut.shopTip": "The shop opens between waves: Full Health and Full Ammo are always on sale, and four perks change every wave — the clock is ticking",

    // ---- touch controls and layout editor ----
    "touch.fire": "FIRE", "touch.aim": "AIM", "touch.interact": "E", "touch.reload": "R", "touch.jump": "JUMP", "touch.sprint": "RUN", "touch.pause": "II",
    "touchcfg.title": "Customize Controls",
    "touchcfg.hide": "Hide",
    "touchcfg.show": "Show",
    "touchcfg.hint": "Drag a button to move it · tap a button once to select it, then resize it below",
    "touchcfg.selected": "Selected",
    "touchcfg.none": "— tap a button to select —",
    "touchcfg.size": "Button size",
    "touchcfg.small": "Small", "touchcfg.medium": "Medium", "touchcfg.large": "Large",
    "touchcfg.resetOne": "Reset this button",
    "touchcfg.opacity": "Button opacity",
    "touchcfg.sens": "Look drag sensitivity",
    "touchcfg.resetAll": "Reset All",
    "touchcfg.done": "Done",
    "touchcfg.confirmReset": "Reset every position, size, opacity and sensitivity to default?",
    "touchcfg.joystick": "Move stick", "touchcfg.fire": "Fire button (FIRE)", "touchcfg.ads": "Aim button", "touchcfg.interact": "Use button (E)",
    "touchcfg.reload": "Reload button (R)", "touchcfg.jump": "Jump button", "touchcfg.sprint": "Run button", "touchcfg.pause": "Pause button",
    "touchcfg.slots": "Weapon row",

    // ---- signs and posters in the world ----
    "world.wallWeight": "Weight: {w}",
    "world.info": "Information",
    "world.schoolName": "BAN NONG SCHOOL",
    "world.welcome": "Welcome",
    "world.banner1": "WIN", "world.banner2": "GO TEAM", "world.banner3": "OUR TEAM",
    "world.home": "HOME", "world.away": "AWAY",
    "world.emergency": "Emergency Dept.",
    "world.emergencySub": "THIS WAY  →",
    "world.triage": "TRIAGE",
    "world.blastDoor": "Blast Door",
    "world.sealed": "SEALED",
    "world.reactor": "Reactor Room",
    "world.coreUnstable": "CORE  UNSTABLE",
    "poster.noRunning": "NO RUNNING",
    "poster.numbers": "1 2 3",
    "poster.abc": "ABC",
    "poster.worldMap": "WORLD MAP",
    "poster.clean": "KEEP IT CLEAN",
    "poster.periodic": "PERIODIC TABLE",
    "poster.exams": "EXAM WEEK!",
    "poster.greens": "EAT YOUR GREENS",
    "notice.1": "NOTICE", "notice.2": "NO CLASS", "notice.3": "SPORTS DAY", "notice.4": "MIDTERMS", "notice.5": "LOST CAT", "notice.6": "CLUBS",
    "sign.extinguisher": "FIRE EXTINGUISHER",
    // round 3: story notes and the Notes Journal
    "menu.journal": "Notes Journal",
    "journal.title": "Notes Journal",
    "journal.found": "Notes found: {n} / {total}",
    "journal.none": "No story notes found here yet.",
    "journal.soon": "The story notes for this level are coming in a later update.",
    "journal.notFound": "Not found yet",
    "notes.keep": "Keep Note",
    "notes.close": "Close",
    "notes.listen": "Listen",
    "notes.stop": "Stop",
    "notes.cefrAria": "CEFR level {level}",
    "notes.kept": "Note kept",
    "notes.keptAgain": "Note kept (already in your journal)",
    "notes.keptText": "Notes Journal: {n} / {total}",
    "prompt.note": "Press {key} to read",
    // round 3: the third floor and its rewards (its keycard and lock: below)
    "banner.gate3Locked": "Locked",
    "banner.thirdFloor": "3rd floor unlocked!",
    "banner.thirdFloorText": "The Vocabulary Lock opens and the grille lifts",
    "prompt.safe": "Press {key} to open the principal's safe", "prompt.safeUsed": "Empty",
    "prompt.trophy": "Press {key} to search the trophy case", "prompt.trophyUsed": "Empty",
    "prompt.coffee": "Press {key} to make a coffee", "prompt.coffeeUsed": "Out of coffee",
    "prompt.radio": "Press {key} to use the radio", "prompt.radioUsed": "The battery is flat",
    "banner.trophy": "Sports Day prize money",
    "banner.trophyText": "+${n}",
    "banner.coffee": "Fresh coffee",
    "banner.coffeeText": "Free perk: {perk} (level {lvl})",
    "banner.coffeeNone": "You already have every perk at its highest level.",
    "banner.radio": "The radio crackles",
    "banner.radioText": "Notes still lying about are marked on your map ({n}).",
    // round 3: the minimap
    "map.north": "N",
    "map.aria": "Minimap",
    // round 3: the campus
    "world.rescueUnit": "DISTRICT RESCUE UNIT",
    "world.checkpoint": "CHECKPOINT",
    "world.checkpointSub": "Evacuation point · Wait here",
    "world.schoolBus": "SCHOOL BUS",
    "world.sportsHall": "SPORTS HALL",
    // round 3: the name over every door (G2)
    "room.classroom": "Classroom", "room.library": "Library", "room.meeting": "Meeting Room", "room.boardroom": "Board Room",
    "room.science": "Science Lab", "room.chemistry": "Chemistry Lab", "room.physics": "Physics Lab",
    "room.music": "Music Room", "room.art": "Art Room", "room.nurse": "Nurse's Office",
    "room.computer": "Computer Room", "room.languageLab": "Language Lab", "room.principal": "Principal's Office",
    "room.canteen": "Canteen", "room.toilets": "Toilets", "room.office": "School Office", "room.deputy": "Deputy Head",
    "room.staffoffice": "Staff Office", "room.detention": "Detention Room", "room.storeroom": "Storeroom",
    "room.changing": "Changing Room", "room.sports": "PE Store", "room.staff": "Staff Room", "room.lounge": "Staff Lounge",
    "room.archive": "Archive", "room.trophy": "Trophy Room", "room.broadcast": "Broadcast Room", "room.stairs": "Stairs to 3rd Floor",
    // round 3: what is written on the boards (lines split at |)
    "board.pastSimple": "Past simple: go - went, see - saw|Yesterday I ____ to the market.",
    "board.vocab": "New words:|abandon, reluctant, inevitable|evacuate, resilient, vivid",
    "board.homework": "Homework: page 42, exercises 3-5|Hand in on Friday!",
    "board.timetable": "EXAM WEEK|Mon: English   Tue: Maths|Wed: Science   Thu: Thai",
    "board.menu": "TODAY'S MENU|Rice soup · Fried chicken|Fresh fruit",
    "board.silence": "SILENCE",
    "board.onAir": "ON AIR",
    "board.groups": "Stay with your group.|Do NOT go outside.|Wait for a teacher.",
    "board.time": "3:17",
    "board.evacuate": "EVACUATION ROUTE|Meet at the football field",
    "board.library": "SILENCE PLEASE|Return all books by Friday",
    "board.physics": "Physics: F = m x a|Newton's laws of motion",
    "board.chemistry": "Chemistry: H2O, NaCl, CO2|Always wear your goggles!",
    "board.music": "Year 8 Choir|Practice: Thursday, 3 pm",
    "board.wellDone": "Well done, Year 9!|Sports Day Champions",
    "board.blank": " ",
    // newer list, round 3 (I3): what the last people here wrote -- in chalk on
    // the boards, in red paint and black marker on the walls (js/wear.js)
    "scrawl.1": "DON'T MAKE A SOUND", "scrawl.2": "THEY KNOW THE WORDS", "scrawl.3": "CLASS DISMISSED. FOREVER.",
    "scrawl.4": "NO ONE IS COMING", "scrawl.5": "STAY IN THE LIGHT", "scrawl.6": "WE WAITED FOR THE BUS",
    "scrawl.7": "GET OUT", "scrawl.8": "HELP US", "scrawl.9": "THEY'RE INSIDE", "scrawl.10": "DON'T OPEN", "scrawl.11": "RUN",
    "scrawl.12": "EXIT ->", "scrawl.13": "SAFE ROOM X", "scrawl.14": "3:17",
    // round 3: places on the campus (the explore objective, the minimap)
    "place.FIELD": "Football Field", "place.GARDEN": "Flower Garden", "place.SALA_FRONT": "Front Sala",
    "place.SALA_FIELD": "Field Sala", "place.SALA_GARDEN": "Garden Sala", "place.CARPARK": "Car Park",
    "place.CHECKPOINT": "Rescue Checkpoint", "place.BACKYARD": "Service Yard",
    // round 4: the lobby
    "lobby.tab.campaign": "CAMPAIGN",
    "lobby.tab.training": "TRAINING & CUSTOM",
    "lobby.featured": "FEATURED",
    "lobby.icon.settings": "Settings", "lobby.icon.leaderboard": "Leaderboard", "lobby.icon.achievements": "Achievements",
    "lobby.icon.armory": "Weapon Log", "lobby.icon.wordlog": "Vocabulary Log", "lobby.icon.journal": "Notes Journal", "lobby.icon.help": "How to Play",
    "lobby.icon.custom": "Custom Vocabulary", "lobby.icon.bosses": "Boss Codex",
    // (B) the short names under the icons (the full ones above are the tooltips)
    "lobby.iconShort.settings": "Settings", "lobby.iconShort.leaderboard": "Ranks", "lobby.iconShort.achievements": "Awards",
    "lobby.iconShort.armory": "Weapons", "lobby.iconShort.wordlog": "Vocab", "lobby.iconShort.journal": "Notes",
    "lobby.iconShort.custom": "Custom", "lobby.iconShort.help": "Help", "lobby.iconShort.bosses": "Bosses",
    "hud.hearShort": "Hear",
    "touch.interactLabel": "Use", "touch.reloadLabel": "Reload", "touch.pauseLabel": "Pause", "touch.knifeLabel": "Knife",
    "touch.fireLabel": "Fire", "touch.aimLabel": "Aim", "touch.jumpLabel": "Jump", "touch.sprintLabel": "Run",
    // (C) Settings: the shop's time between waves
    "settings.gameplay": "Gameplay",
    "settings.shopTime": "Shop time between waves",
    "settings.seconds": "{n} seconds",
    "settings.shopNoLimit": "No limit (wait for Ready)",
    "common.loadFailed": "The game could not start. Check your connection and reload.",
    // (A4) a new version of the game
    "update.title": "New version available",
    "update.text": "A newer version of the game has been downloaded. Reload to start playing it — your progress is saved.",
    "update.reload": "Tap to reload", "update.reloadClick": "Click to reload",
    "update.later": "Later",
    // held upright on a phone or tablet (js/pwa.js)
    "rotate.title": "Rotate your device",
    "rotate.text": "Vocab Zombie is played sideways. Turn your phone or tablet to landscape to keep playing.",
    "lobby.mode.endless": "Endless Mode", "lobby.mode.daily": "Daily Challenge", "lobby.mode.practice": "Practice Mode", "lobby.mode.custom": "Custom Vocabulary",
    "lobby.badge.featured": "FEATURED", "lobby.badge.campaign": "CAMPAIGN", "lobby.badge.survival": "SURVIVAL", "lobby.badge.daily": "DAILY EVENT",
    "lobby.badge.training": "TRAINING", "lobby.badge.creative": "CREATIVE", "lobby.badge.locked": "LOCKED",
    "lobby.desc.school": "The bell rang at 3:17 and nobody went home. Search three floors and a whole campus, read what the survivors left behind, and fight your way to the rescue point.",
    "lobby.desc.hospital": "The lights still hum in the empty wards. Every door hides a patient who did not leave — and a word you need to know.",
    "lobby.desc.bunker": "Deep under the city, the last shelter has gone quiet. Only the hardest words will open the blast doors.",
    "lobby.desc.endless": "No exit, no last wave. Every word from every level, faster and faster, for as long as you can last.",
    "lobby.desc.daily": "One set of words and one seed for everyone today. One try counts for your best score — a new challenge at midnight.",
    "lobby.desc.practice": "No zombies, no clock. Go over the words you miss most, with meanings and pronunciation.",
    "lobby.desc.custom": "Add your own words to any level, or import a whole list, and the zombies will carry them.",
    "lobby.unlock.hospital": "Clear the Abandoned School to unlock",
    "lobby.unlock.bunker": "Clear the Abandoned Hospital to unlock",
    "lobby.lockedShort": "Locked",
    "lobby.best": "High score", "lobby.bestWave": "Best wave", "lobby.notes": "Notes", "lobby.words": "Words mastered",
    "lobby.guns": "Guns found", "lobby.today": "Today's best", "lobby.next": "Next challenge", "lobby.weak": "Words to review",
    "lobby.yourWords": "Your words", "lobby.sets": "Imported lists",
    "lobby.waves": "{n} waves",
    "lobby.meta.endless": "All levels · No end",
    "lobby.meta.practice": "No zombies · Your pace",
    "lobby.meta.custom": "Your words · Any level",
    "lobby.play": "Play",
    "lobby.open": "Open",
    "lobby.tapAgain": "Tap again to",
    "lobby.hint.kb": "<kbd>←</kbd><kbd>→</kbd> Choose · <kbd>Enter</kbd> Select · <kbd>Q</kbd><kbd>E</kbd> Switch tab · <kbd>↑</kbd> Menu",
    "lobby.hint.pad": "<kbd>D-pad</kbd> Choose · <kbd class=\"pad-a\">A</kbd> Select · <kbd>LB</kbd><kbd>RB</kbd> Switch tab · <kbd>↑</kbd> Menu",
    "lobby.hint.touch": "Swipe to choose · Tap the card again to play · Tap a tab to switch",
    "howto.tutorial": "Replay Tutorial",
    "howto.import": "Import Vocabulary",

    // ---- weapon names ----
    "weapon.melee": "Combat Knife",
    "weapon.pistol": "Pistol", "weapon.shotgun": "Shotgun", "weapon.smg": "SMG", "weapon.rifle": "Assault Rifle", "weapon.lmg": "LMG",
    "weapon.sniper": "Sniper", "weapon.railgun": "Piercing Railgun", "weapon.grenadelauncher": "Grenade Launcher",
    "weapon.golden_smg": "Golden Vocabulary SMG", "weapon.school_wall": "Faculty Enforcer", "weapon.hospital_wall": "Trauma Cannon",
    "weapon.bunker_wall": "Vault Breaker", "weapon.hall_monitor": "Hallway Monitor", "weapon.detention_slug": "Detention Slugger",
    "weapon.pop_quiz": "Pop Quiz", "weapon.cafeteria_cleaver": "Cafeteria Cleaver", "weapon.honor_roll": "Honor Roll",
    "weapon.science_fair": "Science Fair", "weapon.art_attack": "Art Attack", "weapon.principals_verdict": "Principal's Verdict",
    "weapon.scrap_spitter": "Scrap Spitter", "weapon.nail_driver": "Nail Driver", "weapon.hall_sweeper": "Hall Sweeper",
    "weapon.chalk_burster": "Chalk Burster", "weapon.detention_deuce": "Detention Deuce", "weapon.rust_repeater": "Rust Repeater",
    "weapon.gym_grinder": "Gym Class Grinder", "weapon.copper_coil": "Copper Coil", "weapon.locker_lancer": "Locker Lancer",
    "weapon.bus_bulldog": "Bus Stop Bulldog", "weapon.thunder_chalk": "Thunder Chalk", "weapon.void_principal": "Void Principal",
    "weapon.prism_lance": "Prism Lance", "weapon.final_bell": "Final Bell", "weapon.meteor_detention": "Meteor Detention",
    "weapon.sterile_slug": "Sterile Slug", "weapon.rebound_pistol": "Rebound Pistol", "weapon.scalpel_smg": "Scalpel SMG",
    "weapon.triage_carbine": "Triage Carbine", "weapon.crash_cart": "Crash Cart", "weapon.iv_repeater": "IV Repeater",
    "weapon.bone_saw": "Bone Saw", "weapon.morphine_mist": "Morphine Mist", "weapon.quarantine_lance": "Quarantine Lance",
    "weapon.autoclave": "Autoclave", "weapon.defib_driver": "Defib Driver", "weapon.vital_sign": "Vital Sign",
    "weapon.code_blue": "Code Blue", "weapon.gauze_gun": "Gauze Gun", "weapon.syringe_spitter": "Syringe Spitter",
    "weapon.plaster_popper": "Plaster Popper", "weapon.oxygen_burst": "Oxygen Burst", "weapon.reflex_hammer": "Reflex Hammer",
    "weapon.dialysis_drum": "Dialysis Drum", "weapon.x_ray_beam": "X-Ray Beam", "weapon.anesthetic_arc": "Anesthetic Arc",
    "weapon.cardiac_coil": "Cardiac Coil", "weapon.plague_thrower": "Plague Thrower", "weapon.gene_splicer": "Gene Splicer",
    "weapon.flatline": "Flatline", "weapon.rebar_repeater": "Rebar Repeater", "weapon.breach_gauge": "Breach Gauge",
    "weapon.scrap_auto": "Scrap Auto", "weapon.service_rifle": "Service Rifle", "weapon.pipe_mortar": "Pipe Mortar",
    "weapon.vent_ripper": "Vent Ripper", "weapon.bolt_thrower": "Bolt Thrower", "weapon.siege_slug": "Siege Slug",
    "weapon.drum_hammer": "Drum Hammer", "weapon.capacitor_lance": "Capacitor Lance", "weapon.thermite_tube": "Thermite Tube",
    "weapon.overwatch": "Overwatch", "weapon.warhead": "Warhead", "weapon.nut_cracker": "Nut Cracker",
    "weapon.chain_feeder": "Chain Feeder", "weapon.blast_door": "Blast Door", "weapon.tri_burst": "Tri-Burst",
    "weapon.sledge_shot": "Sledge Shot", "weapon.rail_spike": "Rail Spike", "weapon.arc_welder": "Arc Welder",
    "weapon.mag_driver": "Mag Driver", "weapon.mortar_pup": "Mortar Pup", "weapon.reactor_core": "Reactor Core",
    "weapon.last_stand": "Last Stand", "weapon.doomsday": "Doomsday",

    // ---- round 3 (H): abilities, the bosses' reward ----
    "ability.dash.name": "Dash",
    "ability.dash.desc": "Burst a few metres the way you are moving (straight ahead if you are standing still). Nothing can hurt you during the dash.",
    "ability.overdrive.name": "Overdrive",
    "ability.overdrive.desc": "Refills your stamina, then for 6 seconds you move 25% faster and sprinting costs no stamina.",
    "ability.vault.name": "Pole Vault",
    "ability.vault.desc": "Leap high and far forward, over the zombies' heads. While you are high in the air they cannot reach you.",
    "ability.rewind.name": "Rewind",
    "ability.rewind.desc": "Snap back to where you stood about 4 seconds ago.",
    "ability.barrier.name": "Barrier",
    "ability.barrier.desc": "A shield soaks up 75% of the damage from bites, traps and bosses for 4 seconds.",
    "ability.smoke.name": "Smoke Bomb",
    "ability.smoke.desc": "A cloud of smoke around you for 5 seconds. Zombies in it lose track of you and wander off without biting.",
    "ability.decoy.name": "Decoy",
    "ability.decoy.desc": "Set up a cardboard double in front of you. Zombies nearby go for it instead of you for 6 seconds.",
    "ability.patch.name": "Patch Up",
    "ability.patch.desc": "Heal 35% of your maximum health over 3 seconds.",
    "ability.freeze.name": "Frost Sprite",
    "ability.freeze.desc": "A little ice helper flies to the zombie in your sights and freezes it solid for 4.5 seconds. It still has to be shot on its own word. A boss thaws in 0.8 seconds.",
    "ability.shockwave.name": "Shockwave",
    "ability.shockwave.desc": "Pushes every zombie within 6 metres away and dazes them for a second. No damage. A boss only staggers.",
    "ability.timewarp.name": "Time Warp",
    "ability.timewarp.desc": "For 5 seconds, zombies within 12 metres of where you stand move at a third of their speed.",
    "ability.glue.name": "Glue Trap",
    "ability.glue.desc": "Spill glue where you are looking. Zombies crossing it crawl at a fifth of their speed for 8 seconds.",
    "ability.flashbang.name": "Flashbang",
    "ability.flashbang.desc": "Dazzles every zombie in front of you (15 metres): they stand still for 2.5 seconds. Bosses are not fooled.",
    "ability.well.name": "Gravity Well",
    "ability.well.desc": "A small vortex where you look pulls nearby zombies together for 3 seconds. Caught in it, they cannot bite.",
    "ability.radar.name": "Word Radar",
    "ability.radar.desc": "For 8 seconds the zombie carrying the word you need glows gold, shows through walls and is marked on the minimap.",
    "ability.whisper.name": "Whisper",
    "ability.whisper.desc": "For 10 seconds the HUD shows the first three letters of the word you need and how long it is.",
    "ability.fifty.name": "Fifty-Fifty",
    "ability.fifty.desc": "For 10 seconds, half of the wrong words on the field are crossed out in grey (✗).",
    "ability.lens.name": "Translator Lens",
    "ability.lens.desc": "For 6 seconds, the zombie you aim at shows its Thai meaning above its word.",
    "ability.resupply.name": "Resupply",
    "ability.resupply.desc": "Instantly fills every gun's magazine and adds one spare magazine to each.",
    "ability.magnet.name": "Magnet",
    "ability.magnet.desc": "Every pickup within 30 metres flies straight to you.",
    "ability.cat.move": "Movement", "ability.cat.defend": "Defense", "ability.cat.control": "Control", "ability.cat.words": "Word help", "ability.cat.support": "Support",
    "ability.cd": "Cooldown {s} s", "ability.cdShort": "{s} s", "ability.dur": "Lasts {s} s",
    "ability.noTarget": "Nothing to use it on",
    "ability.noTarget.freeze": "No zombie in your sights",
    "ability.noTarget.patch": "Already at full health",
    "ability.noTarget.vault": "Already in the air",
    "ability.noTarget.rewind": "Nothing to rewind to yet",
    "ability.noTarget.radar": "No word to find right now",
    "ability.noTarget.whisper": "No word to find right now",
    "ability.noTarget.fifty": "No wrong words to cross out",
    "ability.noTarget.magnet": "No pickups nearby",
    "ability.noTarget.resupply": "No gun to fill",
    "hive.kicker": "BOSS REWARD",
    "hive.title": "Choose an Ability",
    "hive.sub": "Five abilities lie hidden. Pick one — then see what the others were.",
    "hive.hint": "1–5 or arrows + Enter · click or tap a hexagon",
    "hive.hidden": "Hidden ability {n}",
    "hive.revealTitle": "Ability Unlocked!",
    "hive.revealSub": "Yours for the rest of the run. The others go back in the bag — they will not be offered again this run.",
    "hive.notChosen": "Not chosen",
    "hive.useKey": "Use it with {k}",
    "hive.usePad": "Use it with the D-pad {k}",
    "hive.useTouch": "Use it with its button above your weapons",
    "hive.continue": "Continue",
    "hive.full": "You already hold four abilities. Swap one for the new one, or keep the ones you have.",
    "hive.replace": "Swap out {name}",
    "hive.keep": "Keep my abilities",
    "key.ability1": "Ability 1", "key.ability2": "Ability 2", "key.ability3": "Ability 3", "key.ability4": "Ability 4",
    "touchcfg.abilities": "Ability buttons",
    "hud.whisper": " · Starts “{s}…” ({n} letters)",
    "pause.abilities": "Abilities",
    "pause.noAbilities": "No abilities yet — answer the hard word after a boss to earn one.",
    "pause.abilityHint": "Point at, tap or select an ability to see what it does.",

    // ---- round 3 (I): the third floor ----
    "f3.title": "3rd floor ({d}/{n})",
    "f3.open": "The 3rd floor is open",
    "f3.step.second": "Unlock the 2nd floor",
    "f3.step.boss": "Defeat the Wave {n} boss",
    "f3.step.kills": "Kill {n} zombies with the right word",
    "f3.step.notes": "Read {n} story notes",
    "f3.step.keycard": "Find the Floor 3 Keycard on the 2nd floor",
    "f3.step.lock": "Open the Vocabulary Lock (3 hard words)",
    "f3.value.search": "Search the 2nd floor",
    "f3.value.jammed": "Jammed {s}s",
    "f3.hud": "3F {d}/{n}",
    "f3.hud.card": "Keycard on 2F",
    "f3.hud.lock": "Go to the 3F stairs",
    "f3.hud.jammed": "Lock jammed {s}s",
    "prompt.gate3Card": "3rd floor locked · Needs the Floor 3 Keycard · Steps {d}/6 (see Pause)",
    "prompt.gate3Jammed": "Vocabulary Lock jammed · Try again in {s}s",
    "prompt.gate3Lock": "Press {key}: Vocabulary Lock · {n} hard words, {s}s each",
    "banner.gate3Need": "Needs the Floor 3 Keycard · Steps {d}/6 (see Pause)",
    "banner.keycard": "Floor 3 Keycard",
    "banner.keycardText": "It has turned up somewhere on the 2nd floor",
    "banner.keycardTaken": "Keycard found!",
    "banner.keycardTakenText": "Take it to the stairs up to the 3rd floor",
    "banner.lockJammed": "Vocabulary Lock",
    "banner.lockJammedText": "Jammed · Try again in {s}s",
    "banner.lockFail": "Wrong! Jammed for {s}s — then three new words",
    "challenge.lock": "Vocabulary Lock · word {i} of {n}",

    // ---- round 3 (J): the checkpoint ----
    "cp.saved": "Checkpoint Saved - Wave {n}",
    "cp.continueFrom": "Continue from Wave {n}",
    "cp.continueWave": "Continue - Wave {n}",
    "cp.restartFrom1": "Restart from Wave 1",
    "cp.newRun": "New Run (Wave 1)",
    "cp.gameOverNote": "Your checkpoint is safe: continue from Wave {n} as often as you like.",
    "cp.pauseResume": "Checkpoint saved · Progress will resume from Wave {n}",
    "cp.pauseNone": "No checkpoint yet · One is saved after the Wave {n} boss",
    "cp.chooseText": "You have a checkpoint at Wave {n} (saved {when}, score {score}). Continue from there, or start a new run from Wave 1?",
    "cp.deleteTitle": "Delete your checkpoint?",
    "cp.deleteText": "Starting a new run from Wave 1 deletes your checkpoint at Wave {n}. This cannot be undone.",
    "cp.deleteYes": "Delete and start",
    "dialog.yes": "Yes", "dialog.cancel": "Cancel",
    "banner.arenaAmmo": "Ammo supply",
    "banner.arenaAmmoText": "Supply boxes drop in the arena: walk over one for ammo for every gun",
    "lobby.continueWave": "Continue - Wave {n}",
    "lobby.moreChoices": "Continue or new run",
    "leaderboard.continued": "Used Continue (checkpoint)",

    // ---- new series, round 1 (D, F): touch look sensitivity, HUD sizes ----
    "touchcfg.bsens": "Fire / Aim drag sensitivity",
    "touchcfg.hudSizes": "HUD sizes...",
    "settings.touchLookSens": "Touch look sensitivity ({v}x)",
    "settings.btnLookSens": "Fire / Aim button look sensitivity ({v}x)",
    "settings.hudSize": "HUD size",
    "settings.hudSizeBtn": "Adjust HUD Size",
    "hudcfg.title": "HUD Size",
    "hudcfg.hint": "Drag a slider: the HUD around the edges changes as you go. Sizes shrink a little by themselves if they would overlap or leave the screen.",
    "hudcfg.all": "Whole HUD",
    "hudcfg.hp": "Health bar", "hudcfg.stamina": "Stamina bar", "hudcfg.money": "Money", "hudcfg.score": "Score",
    "hudcfg.wave": "Wave and zombies left", "hudcfg.weapon": "Weapon and ammo", "hudcfg.minimap": "Minimap",
    "hudcfg.perks": "Perk icons", "hudcfg.abilities": "Ability icons", "hudcfg.word": "Word to find",
    "hudcfg.fitted": "Shrunk to {p}% to fit this screen",
    "hudcfg.reset": "Reset to Default",
    "hudcfg.done": "Done",

    // ---- new series, round 1 (A): the end-of-wave quiz ----
    "quiz.kicker": "WAVE {n} REVIEW",
    "quiz.correct": "Correct: {x}/{n}",
    "quiz.mistakes": "Mistakes: {x}/{n}",
    "quiz.progress": "Question {i} of {n}",
    "quiz.askEnglish": "Which English word means",
    "quiz.askThai": "What does this word mean?",
    "quiz.right": "Correct!",
    "quiz.wrong": "Not quite. The answer is: {a}",
    "quiz.timeUp": "Time's up. The answer is: {a}",
    "quiz.hint": "1-4 to answer · Enter for the next question",
    "quiz.passed": "Review passed!",
    "quiz.passedSub": "{x} of {n} right: the shop is open.",
    "quiz.failed": "Review failed",
    "quiz.failedSub": "{x} of {n} right: no shop this time. The next wave starts now.",
    "quiz.review": "Words to learn",
    "quiz.noneMissed": "No mistakes!",
    "quiz.continue": "Continue",

    // ---- vocabulary series, round 2: memory boxes, spelling, study sessions ----
    "dialog.ok": "OK",
    "hud.spellMeaning": "Spell the word that means",
    // the spelling pad (js/spell.js)
    "spell.aria": "Spelling bar",
    "spell.back": "Delete a letter",
    "spell.hint": "Hint",
    "spell.enter": "Enter",
    "spell.next": "Next zombie",
    "spell.correctIs": "Correct spelling:",
    "spell.waiting": "Waiting for the next zombie...",
    "spell.noMatch": "No zombie here carries \"{w}\"",
    "spell.double": "double {c}",
    "spell.single": "one {c}",
    "spell.and": " and ",
    "spell.tipHas": "Common IELTS mistake: {w} has {list}",
    "spell.tipNot": "Common IELTS mistake: it is {w}, not {x}",
    "spell.missing": "\"{c}\" after \"{p}\"",
    "spell.missingStart": "\"{c}\" at the start",
    "spell.extra": "no \"{x}\" after \"{p}\"",
    "spell.extraStart": "no \"{x}\" at the start",
    "spell.wrongLetter": "\"{c}\" after \"{p}\", not \"{x}\"",
    "spell.wrongLetterStart": "\"{c}\" at the start, not \"{x}\"",
    "spell.keys.keys": "Type the word · Enter fires · Backspace deletes · Tab: hint (costs points) · Arrow keys walk",
    "spell.keys.touch": "Tap the letters in order · tap a placed letter to take it back · Hint costs points · ⟳ next zombie",
    "spell.keys.pad": "D-pad: choose a letter · A: place · B: take back · X: hint · LB / RB: next zombie",
    "spell.glanceTitle": "Spell it!",
    "spell.glanceType": "Bullets can't stop this zombie: type its word and press Enter",
    "spell.glanceTiles": "Bullets can't stop this zombie: put its word together from the letters",
    "spell.reloadTitle": "Spell to reload",
    "spell.reloadKeys.keys": "Type the English word, then Enter · right: full magazine · wrong: half",
    "spell.reloadKeys.touch": "Tap the letters in order · right: full magazine · wrong: half",
    "spell.reloadKeys.pad": "D-pad and A to place the letters · right: full magazine · wrong: half",
    // the Learning Modes window (js/study.js, js/learnmodes.js)
    "learn.title": "Learning Modes",
    "learn.sub": "A short session on the school grounds with a level's words. New words come a few at a time, and the ones you know come back when they are due.",
    "learn.modeHead": "How you answer",
    "learn.levelHead": "Words from",
    "learn.start": "Start",
    "learn.words": "{n} words",
    "learn.preset.classic": "Classic",
    "learn.presetDesc.classic": "Read the Thai meaning, shoot the zombie carrying the English word.",
    "learn.preset.spelling": "Spelling",
    "learn.presetDesc.spelling": "Every zombie shows a Thai meaning: spell its English word to take it down.",
    "learn.preset.paraphrase": "Paraphrase",
    "learn.presetDesc.paraphrase": "An English definition: shoot the word it describes.",
    "learn.preset.listening": "Listening",
    "learn.presetDesc.listening": "Hear the word: shoot the zombie that carries it.",
    "learn.preset.dictation": "Dictation",
    "learn.presetDesc.dictation": "Hear the word: spell it.",
    "learn.preset.context": "Context",
    "learn.presetDesc.context": "A sentence with a gap: shoot the word that fills it.",
    "learn.preset.adaptive": "Adaptive",
    "learn.presetDesc.adaptive": "Chosen for each word: new words are shot, words you know well are spelt.",
    // a look-alike shot by mistake (E)
    "learn.lookAlikeTitle": "That was {x}!",
    "learn.lookAlikeText": "{x} = {xm} · you wanted {y} = {ym}",
    // the vocabulary log: pairs the player mixes up (E2)
    "learn.confusedWith": "You often confuse this with: {x}",
    "learn.box": "Memory box {n}/5",
    "learn.boxMastered": "Mastered",
    "learn.boxNew": "New",
    "learn.due": "Review due {when}",
    "learn.dueToday": "today",
    "learn.dueTomorrow": "tomorrow",
    "learn.dueIn": "in {n} days",
    // study sessions (js/study.js)
    "study.reviewTitle": "Daily Review",
    "study.learnTitle": "Learning",
    "study.learnTitleMode": "{mode} · {level}",
    "study.caughtUpTitle": "All reviewed!",
    "study.caughtUpText": "Nothing more is due today. Tomorrow: {n} words.",
    "study.hud": "{title} · {n}/{total}",
    "study.doneReview": "Review done!",
    "study.doneLearn": "Session done!",
    "study.died": "Bitten! The session is over",
    "study.bitten": "Too slow!",
    "study.bittenText": "{m} = {w}",
    "study.bittenBack": "{m} = {w} · it will come back",
    "study.statWords": "Words answered",
    "study.statRight": "Right first time",
    "study.statScore": "Score",
    "study.statStreak": "Review streak",
    "study.day": "{n} day",
    "study.days": "{n} days",
    "study.continueMore": "Continue ({n} more due)",
    "study.again": "Another Session",
    "study.toLobby": "Back to Lobby",
    "study.introTitle": "How spelling works",
    "study.introGo": "Got it",
    "study.intro.keys.1": "Each zombie shows a Thai meaning over its head. Type its English word in the bar at the bottom of the screen.",
    "study.intro.keys.2": "Press Enter: if a zombie on screen carries that word, your gun fires at it. Bullets alone can't stop these zombies.",
    "study.intro.keys.3": "Every letter key goes into the bar, so walk with the arrow keys. Backspace deletes, Tab puts in the next letter (it costs points).",
    "study.intro.keys.4": "The dashes show how many letters the word has. A wrong spelling shows which letters were off, and the right word.",
    "study.intro.touch.1": "Each zombie shows a Thai meaning over its head. The bar at the bottom works on one of them: its meaning is at the top of the bar.",
    "study.intro.touch.2": "Tap its letters in the right order. Tap a placed letter to take it back, with the ones after it.",
    "study.intro.touch.3": "When every letter is in, the gun fires by itself. Hint puts in the next letter (it costs points); ⟳ moves to another zombie.",
    "study.intro.touch.4": "Keep moving with the joystick. A wrong spelling shows which letters were off, and the right word.",
    "study.intro.pad.1": "Each zombie shows a Thai meaning over its head. The bar at the bottom works on one of them: its meaning is at the top of the bar.",
    "study.intro.pad.2": "D-pad to choose a letter, A to place it, B to take the last one back.",
    "study.intro.pad.3": "When every letter is in, the gun fires by itself. X puts in the next letter (it costs points); LB / RB move to another zombie.",
    "study.intro.pad.4": "The left stick still walks and the right stick looks. A wrong spelling shows which letters were off, and the right word.",
    // the tutorial's spelling cards (js/tutorial.js)
    "tut.spell.title": "Spell to shoot",
    "tut.spell.desk": "Each zombie's Thai meaning floats over its head. Type its English word in the bar at the bottom and press Enter: your gun fires at the zombie that carries it.",
    "tut.spell.touch": "Each zombie's Thai meaning floats over its head. Tap the letters of its word in order in the bar at the bottom: when the word is complete, your gun fires.",
    "tut.spell.pad": "Each zombie's Thai meaning floats over its head. Choose its letters with the D-pad and place them with A: when the word is complete, your gun fires.",
    "tut.spellMove.title": "Keep moving",
    "tut.spellMove.desk": "Letters go into the spelling bar, so walk with the arrow keys. Tab puts in the next letter, but costs points.",
    "tut.spellMove.touch": "Walk with the joystick while you spell. Hint puts in the next letter, but costs points; ⟳ switches to another zombie.",
    "tut.spellMove.pad": "The left stick walks while you spell. X puts in the next letter, but costs points; LB / RB switch to another zombie.",
    // the lobby's Training cards (js/lobby.js)
    "lobby.mode.review": "Daily Review",
    "lobby.mode.learn": "Learning Modes",
    "lobby.badge.review": "EVERY DAY",
    "lobby.badge.learn": "LEARN",
    "lobby.desc.review": "The words due for review today, on the school grounds: a few minutes, no shop, no boss. One session a day keeps your streak going.",
    "lobby.desc.learn": "Choose how you answer — shoot, spell, or let the game choose for each word — and whose words to learn.",
    "lobby.meta.review": "{n} due today",
    "lobby.meta.reviewNone": "All reviewed",
    "lobby.meta.learn": "Shoot · Spell · Listen · Context",
    "lobby.due": "Due today", "lobby.streak": "Streak", "lobby.bestStreak": "Best streak", "lobby.tomorrow": "Tomorrow",
    "lobby.learning": "Learning", "lobby.known": "Known", "lobby.masteredBox": "Mastered",
    // settings
    "settings.spellReload": "Spell to Reload: spell a word of the wave to reload (right: a full magazine, wrong: half)",

    // ---- vocabulary series, round 3: English clues, listening, context, the vocabulary card ----
    // the clue panel at the top
    "hud.clue.definition": "≈ similar meaning: shoot the word",
    "hud.clue.definitionSpell": "≈ similar meaning: spell the word",
    "hud.clue.cloze": "Fill the gap: shoot the word",
    "hud.clue.audio": "Listen: shoot its meaning",
    "hud.clue.audioSpell": "Listen: spell what you hear",
    "hud.showThai": "Show the Thai meaning (a helper: the word's box will not move)",
    "hud.showThaiShort": "Thai",
    "hud.playedOnce": "Play Once: you have heard this word",
    "spell.hearAgain": "Hear it again",
    "spell.keys.hear.keys": "{key}: hear it again",
    "spell.keys.hear.touch": "🔊 hear it again",
    "spell.keys.hear.pad": "View: hear it again",
    "spell.thaiShort": "Thai",
    "key.replay": "Hear the word again",
    "key.thaiHint": "Show the Thai of an English clue",
    // after a wrong answer
    "learn.heardTitle": "You heard:",
    "learn.heardText": "{w} · {s} = {m}",
    "learn.formTitle": "Not {x}!",
    "learn.formText": "Wrong form: the sentence needs {y}, not {x}",
    // settings (F, G3)
    "settings.highlightTarget": "Highlight the word to shoot in yellow (a helper: answers will not move a word's memory box)",
    "settings.clueThai": "Thai meaning with English clues",
    "settings.clueThaiAuto": "While a word is new (box 1-2)",
    "settings.clueThaiAlways": "Always show",
    "settings.clueThaiNever": "Never show",
    "settings.accent": "Accent of the spoken words",
    "settings.accent.mixed": "Mixed",
    "settings.accent.british": "British",
    "settings.accent.american": "American",
    "settings.accent.australian": "Australian",
    "settings.accentVoices": "English voices on this device: {list}",
    "settings.accentMissing": "This device has no {a} voice, so another English voice is used.",
    "settings.accentNone": "No English voice found on this device yet.",
    "settings.speechSpeed": "Speed of the spoken words",
    "settings.speedNormal": "Normal",
    "settings.speedSlow": "Slow (0.8x)",
    "settings.playOnce": "Play Once: hear a spoken clue only once, as in the IELTS Listening test",
    // the eight kinds of question (H5)
    "q.th2en": "Which English word means",
    "q.en2th": "What does this word mean?",
    "q.def2word": "Which word matches this definition?",
    "q.cloze": "Which word fills the gap?",
    "q.colloc": "Which word completes the phrase?",
    "q.paraphrase": "Which word can replace the underlined words?",
    "q.listen": "Listen: what does the word mean?",
    "q.spell": "Spell the English word for",
    "q.hearAgain": "Hear again",
    "quiz.hintSpell": "Type the word, Enter to answer · Backspace deletes · Tab: hint",
    "quiz.next": "Next",
    "challenge.continue": "Continue",
    // the vocabulary card (H2) and the mini card (H3, H4)
    "card.title": "Vocabulary Card",
    "card.peekTitle": "From the word bank",
    "card.full": "Full Card",
    "card.open": "Open the vocabulary card for {word}",
    "card.hear": "Hear the word",
    "card.hearSentence": "Hear the sentence",
    "card.synonyms": "Similar:",
    "card.examples": "Examples",
    "card.collocations": "Collocations",
    "card.family": "Word family",
    "card.dontConfuse": "Don't confuse with",
    "card.youConfused": "you mixed these up",
    "card.spelling": "Watch the spelling: {w} (not {x})",
    "card.awl": "AWL sublist {n}",
    "card.topicWord": "IELTS topic word",
    "card.from": "from {w}",
    "pos.n": "noun", "pos.v": "verb", "pos.adj": "adjective", "pos.adv": "adverb", "pos.prep": "preposition", "pos.conj": "conjunction",
    // the first time in each newer mode ({replay}, {thai}: their keys)
    "study.mode.paraphrase.1": "The box at the top gives an English definition (≈ similar meaning) instead of the Thai. Shoot the zombie with the word it describes.",
    "study.mode.paraphrase.2": "New words show the Thai under it. From box 3 it is English only: Thai ({thai}) shows it, but then the answer does not move the word's box.",
    "study.mode.listening.1": "No English on the zombies: they carry Thai meanings. Listen to the word, then shoot the zombie with its meaning.",
    "study.mode.listening.2": "Hear it again with {replay} or 🔊. Settings: accent, speed, and Play Once to hear each word only once.",
    "study.mode.dictation.1": "The zombies have no labels. Aim at one to hear its word (on touch or a controller, the bar picks one).",
    "study.mode.dictation.2": "Spell what you hear. Hear it again with {replay} or 🔊. A wrong spelling shows the word in syllables and says it again.",
    "study.mode.context.1": "The box at the top shows a sentence with a gap. Shoot the zombie with the word that fills it.",
    "study.mode.context.2": "Watch the form: indicate, indication, indicative... only one of them fits the sentence.",
    "study.mode.adaptive.1": "Each word is asked its own way, by how well you know it: new words in Thai, then English definitions and sentences, then spelling and dictation.",
    "study.mode.adaptive.2": "The box at the top always says which: the Thai meaning, ≈ a definition, a sentence with a gap, or a word to listen to.",
  },
};

G.T = function (key, vars) {
  const table = G.STRINGS[G.lang] || G.STRINGS.en;
  let s = table[key];
  if (s == null) s = G.STRINGS.en[key];
  if (s == null) { if (!G._missingKeys) G._missingKeys = {}; G._missingKeys[key] = true; return key; }
  if (vars) s = s.replace(/\{(\w+)\}/g, (m, k) => (vars[k] != null ? vars[k] : m));
  return s;
};

// fill the static page: data-i18n (text), data-i18n-html, data-i18n-aria
G.applyStaticStrings = function (root) {
  root = root || document;
  root.querySelectorAll("[data-i18n]").forEach((el) => { el.textContent = G.T(el.getAttribute("data-i18n")); });
  root.querySelectorAll("[data-i18n-html]").forEach((el) => { el.innerHTML = G.T(el.getAttribute("data-i18n-html")); });
  root.querySelectorAll("[data-i18n-aria]").forEach((el) => { el.setAttribute("aria-label", G.T(el.getAttribute("data-i18n-aria"))); });
  document.documentElement.lang = G.lang;
};

// names and labels carried on game data, set from the table by id
G.localizeData = function () {
  (G.LEVELS || []).forEach((l) => { l.name = G.T("level." + l.id); });
  if (G.WEAPON_DEFS) Object.values(G.WEAPON_DEFS).forEach((d) => { d.name = G.T("weapon." + d.id); });
  if (G.MELEE_DEF) G.MELEE_DEF.name = G.T("weapon.melee");
  (G.ACHIEVEMENTS || []).forEach((a) => { a.name = G.T("ach." + a.id + ".name"); a.desc = G.T("ach." + a.id + ".desc"); });
  (G.SHOP_ITEMS || []).forEach((it) => { it.label = G.T("shopItem." + it.id); });
  if (G.RARITY) Object.values(G.RARITY).forEach((r) => { r.label = G.T("rarity." + r.key); });
  (G.WEIGHT_CLASSES || []).forEach((w) => { w.label = G.T("weight." + w.key); });
};

// Signs and posters are drawn on fixed-size canvases, and a translation can be
// longer than the text they were laid out for: shrink the font until it fits.
G.fitFont = function (ctx, text, px, maxW, family) {
  const f = (p) => `bold ${p}px ${family || "sans-serif"}`;
  ctx.font = f(px);
  while (px > 10 && ctx.measureText(text).width > maxW) ctx.font = f(--px);
  return px;
};

// before G.Game.init (registered earlier, so it runs first)
window.addEventListener("DOMContentLoaded", () => { G.localizeData(); G.applyStaticStrings(); });
