// ===================================================================
// Every piece of text the player sees, in one place
// -------------------------------------------------------------------
//   G.T("key", { name: value })   the string for `key` in G.lang, with
//                                 {name} placeholders filled in
//   data-i18n="key"               static HTML text (data-i18n-html for text
//                                 with markup, data-i18n-aria for aria-label)
//   G.localizeData()              names and labels that live on game data
//                                 (levels, weapons, achievements, shop items,
//                                 rarity and weight labels) -- by id, so no
//                                 save data ever depends on the text
// The Thai meanings of the vocabulary are NOT here: they are the learning
// content and stay in js/data/words_*.js. To add a language, add a block
// beside `en` with the same keys and set G.lang; anything missing falls
// back to English.
// ===================================================================
window.G = window.G || {};
G.lang = "en";
G.STRINGS = {
  en: {
    // ---- main menu ----
    "menu.title": "VOCAB <span class=\"accent\">ZOMBIE</span>",
    "menu.subtitle": "IELTS Survival FPS",
    "menu.start": "Start Game",
    "menu.practice": "Practice Mode",
    "menu.daily": "Daily Challenge",
    "menu.endless": "Endless Mode",
    "menu.leaderboard": "Leaderboard",
    "menu.achievements": "Achievements",
    "menu.vocablog": "Word Log",
    "menu.weaponlog": "Armory",
    "menu.import": "Import Vocabulary",
    "menu.customvocab": "Custom Vocabulary",
    "menu.howto": "How to Play",
    "menu.tutorial": "Replay Tutorial",
    "menu.settings": "Settings",
    "menu.footer": "v0.1 · Made with Three.js",
    "common.back": "Back",
    "common.mainMenu": "Main Menu",
    "common.loading": "Loading...",
    "common.level": "Level {n}",
    "common.levelNamed": "Level {n}: {name}",
    "common.unknown": "unknown",

    // ---- level select ----
    "levels.title": "Select Level",
    "levels.back": "Back to Main Menu",
    "levels.info": "{waves} waves · Difficulty {diff}x",
    "levels.best": "Best score: {score}",
    "levels.locked": "🔒 Clear the previous level to unlock",
    "level.1": "Abandoned School",
    "level.2": "Abandoned Hospital",
    "level.3": "Underground Bunker",
    "level.daily": "Daily Challenge",
    "level.endless": "Endless",

    // ---- how to play ----
    "howto.title": "How to Play",
    "howto.body": "<p>The top of the screen shows the <strong>Thai meaning</strong> of a word — find the zombie carrying the English word with that meaning and shoot it!</p>"
      + "<ul><li><b>WASD</b> move, <b>Mouse</b> look, <b>Left click</b> shoot, <b>Hold right click</b> aim (zoom)</li>"
      + "<li><b>R</b> reload, <b>E</b> use / pick up, <b>Shift</b> sprint (uses the blue stamina bar, which refills when you stop)</li>"
      + "<li><b>1</b> knife (unlimited melee), <b>2-5</b> switch guns (<b>6-7</b> with the Extra Weapon Slot perk), or the <b>mouse wheel</b></li>"
      + "<li><b>ESC</b> pause</li>"
      + "<li>Controller: <b>RT</b> shoot, <b>LT</b> aim, <b>A</b> jump, <b>X</b> reload, <b>Y</b> use, <b>LB / RB</b> switch guns, <b>Menu</b> pause</li>"
      + "<li>Right zombie = score + money / wrong zombie = you lose health and the rest speed up</li>"
      + "<li>Between waves the shop always sells Full Health and Full Ammo, plus four perks that change every wave</li></ul>",

    // ---- settings ----
    "settings.title": "Settings",
    "settings.controls": "Controls",
    "settings.controlMode": "Control mode",
    "settings.controlAuto": "Automatic",
    "settings.controlDesktop": "Desktop Controls",
    "settings.controlTouch": "Touch Controls",
    "settings.mouseSens": "Mouse sensitivity ({v})",
    "settings.touchLayout": "Touch controls (position / size / opacity / sensitivity)",
    "settings.touchLayoutBtn": "Customize Controls",
    "settings.keybinds": "Key Bindings",
    "settings.resetKeys": "Reset to Default",
    "settings.audio": "Audio",
    "settings.sfxVolume": "Sound effects (guns, zombies, footsteps) ({v}%)",
    "settings.musicVolume": "Music ({v}%)",
    "settings.ambientVolume": "Ambience ({v}%)",
    "settings.speechVolume": "Word pronunciation ({v}%)",
    "settings.speechMode": "Read words aloud automatically",
    "settings.speechAfter": "After a correct answer (recommended)",
    "settings.speechBefore": "As soon as a new word appears (easier)",
    "settings.speechOff": "Off",
    "settings.speechTest": "Test Pronunciation",
    "settings.performance": "Performance",
    "settings.fpsCap": "FPS Cap",
    "settings.unlimited": "Unlimited",
    "settings.showFps": "Show FPS counter",
    "settings.showDraws": "Show draw call count",
    "settings.quality": "Graphics quality",
    "settings.qVlow": "Very Low", "settings.qLow": "Low", "settings.qMedium": "Medium", "settings.qHigh": "High", "settings.qVhigh": "Very High",
    "settings.gameSpeed": "Game speed ({v}x)",
    "settings.accessibility": "Accessibility",
    "settings.fontSize": "Text size",
    "settings.fontSmall": "Small", "settings.fontMedium": "Medium", "settings.fontLarge": "Large",
    "settings.colorblind": "Colorblind mode (adds rarity icons)",
    "settings.headBob": "Camera bob while walking/running ({v}%)",
    "settings.headBobOff": "Turn off camera bob entirely (for motion sickness)",
    "settings.vocabulary": "Vocabulary",
    "settings.customVocab": "Your own words ({n} added)",
    "settings.customVocabBtn": "Custom Vocabulary",
    "settings.saveData": "Save Data",
    "settings.exportSave": "Export Save",
    "settings.importSave": "Import Save",
    "key.forward": "Forward", "key.back": "Back", "key.left": "Left", "key.right": "Right", "key.sprint": "Sprint", "key.jump": "Jump",
    "key.reload": "Reload", "key.interact": "Interact", "key.melee": "Knife", "key.slot2": "Weapon slot 2", "key.slot3": "Weapon slot 3",
    "key.slot4": "Weapon slot 4", "key.slot5": "Weapon slot 5", "key.slot6": "Weapon slot 6 (perk)", "key.slot7": "Weapon slot 7 (perk)",
    "key.pause": "Pause",
    "save.importFailed": "Import failed: {msg}",
    "save.importConfirm": "Importing will overwrite ALL of your current progress.\n\n"
      + "File to import (exported {when}):\n"
      + "  Levels unlocked {al} · Words with stats {aw} · Achievements {aa} · Guns found {ag}\n\n"
      + "Current progress that will be replaced:\n"
      + "  Levels unlocked {bl} · Words with stats {bw} · Achievements {ba} · Guns found {bg}\n\n"
      + "Import this save?",
    "save.importDone": "Save imported",
    "save.persistFailTitle": "Can't save progress",
    "save.persistFailText": "The browser won't store data (private mode?) — use Export Save to keep a copy",
    "save.errRead": "Couldn't read the file",
    "save.errJson": "This file isn't JSON",
    "save.errNotSave": "This file isn't a Vocab Zombie save",
    "save.errCorrupt": "The save data in this file is damaged",

    // ---- leaderboard / achievements ----
    "leaderboard.title": "Leaderboard",
    "leaderboard.daily": "Daily",
    "leaderboard.endless": "Endless",
    "leaderboard.empty": "No scores yet",
    "achievements.title": "Achievements",
    "achievements.unlocked": "🏅 Achievement unlocked!",
    "ach.streak50.name": "Word Scholar", "ach.streak50.desc": "Answer 50 words correctly in a row",
    "ach.secret_crate.name": "Golden Fortune", "ach.secret_crate.desc": "Open a Secret/Legendary weapon crate",
    "ach.no_hit_level.name": "Untouchable", "ach.no_hit_level.desc": "Clear a level without a zombie ever touching you",
    "ach.all_levels.name": "Zombie Conqueror", "ach.all_levels.desc": "Clear every level in the game",
    "ach.first_boss.name": "Boss Hunter", "ach.first_boss.desc": "Defeat your first boss",
    "ach.endless_10.name": "Iron Will", "ach.endless_10.desc": "Survive to wave 10 in Endless Mode",
    "ach.notes_level1.name": "Keeper of Stories", "ach.notes_level1.desc": "Collect all 20 story notes at the Abandoned School",
    "ach.notes_level2.name": "Case Notes", "ach.notes_level2.desc": "Collect all 20 story notes at the Abandoned Hospital",
    "ach.notes_level3.name": "Classified", "ach.notes_level3.desc": "Collect all 20 story notes in the Underground Bunker",

    // ---- word log ----
    "vocablog.title": "Word Log",
    "vocablog.unseen": "Not seen yet",
    "vocablog.right": "Right {n}",
    "vocablog.wrong": "Wrong {n}",
    "vocablog.hear": "Hear {word}",
    "vocablog.custom": "Yours",

    // ---- armory (weapon log) ----
    "weaponlog.title": "Armory",
    "weaponlog.wall": "🔒 Wall guns in this level ({n})",
    "weaponlog.box": "🎴 Mystery box (${cost} a try)",
    "weaponlog.locked": "Locked",
    "weaponlog.odds": "Drop chance: {p}",
    "weaponlog.damage": "Damage: {d}",
    "weaponlog.pellets": " x{n} pellets",
    "weaponlog.rate": "Fire rate: {r}/s",
    "weaponlog.mag": "Magazine: {n}",
    "weaponlog.dps": "Est. DPS: {n}",
    "weaponlog.price": "Price: ${p}",
    "weaponlog.listen": "🔊 Listen",
    "weapon.mode": "Mode: {m}",
    "weapon.weight": "Weight: {w} ({v})",
    "weapon.speedPenalty": "Speed -{p}%",
    "weapon.noPenalty": "No speed penalty",
    "weapon.reload": "Reload: {s}s",
    "weapon.recoil": "Recoil: {r}",
    "weapon.pierce": "pierces",
    "weapon.splash": "area blast",
    "fire.melee": "Melee",
    "fire.charge": "Charge",
    "fire.splash": "Explosive",
    "fire.pellets": "Buckshot x{n}",
    "fire.scope": "Sniper (scoped)",
    "fire.burst": "{n}-round burst",
    "fire.pierce": "Pierces {n}",
    "fire.pierceAll": "Pierces all",
    "fire.auto": "Automatic",
    "fire.semi": "Semi-auto",
    "weight.light": "Light", "weight.medium": "Medium", "weight.heavy": "Heavy", "weight.very_heavy": "Very heavy",
    "rarity.common": "COMMON", "rarity.uncommon": "UNCOMMON", "rarity.rare": "RARE", "rarity.epic": "EPIC", "rarity.secret": "SECRET",

    // ---- import vocabulary ----
    "import.title": "Import Vocabulary",
    "import.fileHint": "Upload a .csv or .txt file with one <code>english,Thai meaning</code> pair per line",
    "import.ocrHint": "Or take a photo of a vocabulary page (basic OCR — needs internet the first time to load the library):",
    "import.save": "Import Words",
    "import.dest": "Add these words to",
    "import.destPractice": "A practice set (Practice Mode only)",
    "import.destLevel": "{level} — the level's word list",
    "import.sumPractice": "Words in the new practice set: {n}.",
    "import.sumLevel": "Words added to {level}: {n}.",
    "import.sumDupes": "Left out as duplicates ({n}):",
    "import.sumInvalid": "Left out as unusable ({n}):",
    "import.whyDup": "already in {level}",
    "import.whyDupFile": "repeated in this file",
    "import.sumSame": "Added, with the same Thai meaning as another word in the level (the two are never on the field together): {words}",
    "import.sets": "Imported Word Sets",
    "import.more": "... and {n} more",
    "import.none": "No valid words found",
    "import.ocrLoading": "Loading the OCR library (may take a moment the first time)...",
    "import.ocrReading": "Reading text from the image...",
    "import.ocrDone": "Done — check and fix the words before saving",
    "import.ocrFailed": "OCR failed: {msg} — try a CSV file instead",
    "import.ocrNoLib": "Couldn't load the OCR library (needs internet) — use a CSV file instead",
    "import.saved": "Word set saved — you can use it in Practice Mode",
    "import.setRow": "{name} ({n} words)",
    "import.delete": "Delete",
    "import.empty": "No imported word sets yet",

    // ---- practice mode ----
    "practice.title": "Practice Mode",
    "practice.quit": "End Practice",
    "practice.choose": "Choose a word set to practise:",
    "practice.weak": "Words I often get wrong",
    "practice.start": "Start Practice",
    "practice.notEnough": "This word set doesn't have enough words to practise (needs at least 4 meanings)",
    "practice.done": "Practice complete! {c}/{n} correct",
    "practice.correct": "Correct!",
    "practice.wrong": "Wrong — the answer is \"{a}\"",

    // ---- results ----
    "result.gameOver": "GAME OVER",
    "result.victory": "VICTORY!",
    "result.retry": "Retry",
    "result.playAgain": "Play Again",
    "result.levelSelect": "Level Select",
    "result.score": "Score",
    "result.wave": "Wave reached",
    "result.correct": "Correct",
    "result.wrong": "Wrong",
    "result.money": "Money earned",
    "result.review": "Words to review",
    "result.wrongTimes": "wrong {n}×",
    "result.perfect": "Great job — no wrong answers!",

    // ---- HUD ----
    "hud.shootMeaning": "Shoot the word meaning",
    "hud.hearAgain": "Hear the word again",
    "hud.boss": "BOSS",
    "hud.zombieBoss": "ZOMBIE BOSS",
    "hud.meaning": "Meaning: {m}",
    "hud.bossHintTouch": "Tap the right answer",
    "hud.bossHintDesk": "Click an answer or press 1-4",
    "hud.skipTutorial": "Skip tutorial",
    "hud.combo": "COMBO x{n}",
    "hud.comboSaved": "🛡️ COMBO SAVED x{n}",
    "hud.resume": "Click the screen to resume",
    "hud.interact": "Press {key} to interact",
    "hud.answerToUnlock": "Answer to unlock",
    "hud.waiting": "Waiting for zombies...",
    "hud.hintFirst": "  (starts with \"{c}\")",
    "hud.hintLen": "  (starts with \"{c}\", {n} letters)",
    "hud.levelWave": "{level} · Wave {wave}",
    "hud.overtime": " (overtime)",
    "hud.objectives": "Objectives {d}/{n}",
    "hud.zombies": "Zombies: {n}",
    "hud.ammoMelee": "∞",
    "hud.fps": "{n} FPS",
    "hud.draws": "{n} draw calls",
    "hud.tris": "{n}k tris",

    // ---- prompts ({key}: the interact key, E on touch, Y on a controller) ----
    "prompt.wordDoor": "Press {key} to try the door (answer a word)",
    "prompt.buttonDone": "Pressed",
    "prompt.button": "Press {key} to push the button",
    "prompt.crate": "Press {key} to open the crate",
    "prompt.trap": "Press {key} to disarm the trap (answer a word)",
    "prompt.hatch": "Press {key} to open the hatch (answer a word)",
    "prompt.doorClose": "Press {key} to close",
    "prompt.doorOpen": "Press {key} to open",
    "prompt.mystery": "Press {key} to roll a gun (${cost})",
    "prompt.notEnough": " - not enough money",
    "prompt.wallGun": "Press {key} to buy {name} (${price}{short}) · {weight}",
    "prompt.pickUp": "Press {key} to pick up {name}",
    "prompt.pickUpTimer": " ({s}s)",

    // ---- word challenges (doors, crates, traps, hatches) ----
    "challenge.crate": "Answer to unlock the crate",
    "challenge.door": "Answer to open the door",
    "challenge.trap": "Answer to disarm the trap",
    "challenge.hatch": "Answer to open the hatch",

    // ---- banners and messages during play ----
    "banner.unlocked": "Unlocked",
    "banner.objectivesLeft": "Objectives not complete!",
    "banner.objectivesLeftText": "Zombies will keep coming until every objective is done (see the HUD / pause screen)",
    "banner.noMoney": "Not enough money",
    "banner.noMoneyText": "Costs ${cost} · you have ${have}",
    "banner.upstairs": "2nd floor unlocked!",
    "banner.upstairsText": "{n} zombies down",
    "banner.explored": "All explored!",
    "banner.exploredText": "Entered {n} rooms",
    "banner.key": "Key found!",
    "banner.keyText": "{k} / {n} keys",
    "banner.allObjectives": "Objectives complete!",
    "banner.clearThisWave": "Clear this wave to finish the level",
    "banner.surviveAll": "Survive every wave to finish the level",
    "banner.secondLife": "Back on your feet — once per wave",

    // ---- objectives ----
    "obj.title": "Level objectives ({d}/{n})",
    "obj.survive": "Survive all {n} waves",
    "obj.correct": "Answer at least {n} words correctly",
    "obj.accuracy": "Word accuracy of {p}% or better",
    "obj.explore": "Explore {n} rooms or places",
    "obj.keys": "Find the {n} hidden keys",
    "obj.boss": "Defeat the level boss",
    "obj.notes": "Read {n} story notes",
    "obj.bossDone": "Done",
    "obj.bossNot": "Not yet",

    // ---- shop ----
    "shop.title": "Shop",
    "shop.timer": "Next wave in {s}s",
    "shop.money": "Money: ",
    "shop.continue": "Start Next Wave",
    "shop.bonus": "Wave {w} cleared · bonus +${b}",
    "shop.level": "Level: {s}/{m}",
    "shop.owned": "Owned",
    "shop.max": "MAX",
    "shop.buy": "Buy",
    "shop.essentials": "Always Available",
    "shop.perks": "Perks This Wave",
    "shop.armory": "Armory",
    "shop.perkLevel": "Lv {l}/{m}",
    "shop.nextLevel": "Next level:",
    "shop.full": "Already full",
    "shop.interest": "interest +${v}",
    "shopItem.heal": "Full Health",
    "shopItem.heal.desc": "Back to full health ({hp}/{max} now)",
    "shopItem.ammo_refill": "Full Ammo",
    "shopItem.ammo_refill.desc": "A full magazine and full reserve for every gun you carry",
    "shopItem.dmg_up": "Damage +15%",
    "shopItem.dmg_up.desc": "Your {w} hits 15% harder",
    "shopItem.firerate_up": "Fire Rate +10%",
    "shopItem.firerate_up.desc": "Your {w} fires 10% faster",
    "shopItem.mag_up": "Magazine +20%",
    "shopItem.mag_up.desc": "Your {w} holds 20% more rounds",
    "shopItem.unlock_shotgun": "Unlock Shotgun",
    "shopItem.unlock_shotgun.desc": "Into a free slot — or you choose which gun to swap first",
    "shopItem.unlock_smg": "Unlock SMG",
    "shopItem.unlock_smg.desc": "Into a free slot — or you choose which gun to swap first",
    "shopItem.unlock_rifle": "Unlock Rifle",
    "shopItem.unlock_rifle.desc": "Into a free slot — or you choose which gun to swap first",
    "shopItem.crate_common": "Weapon Crate",
    "shopItem.crate_common.desc": "A random gun from this level, any rarity",

    // ---- perks (js/perks.js): {a} and {b} are the figures for the level ----
    "perkCat.vocab": "Vocabulary", "perkCat.move": "Movement", "perkCat.shoot": "Shooting", "perkCat.survive": "Survival", "perkCat.money": "Economy",
    "perk.perk_hint.name": "Hint Reader",
    "perk.perk_hint.desc1": "The word prompt shows the first letter of the word to shoot.",
    "perk.perk_hint.desc2": "The word prompt shows the first letter of the word to shoot and how many letters it has.",
    "perk.focus_time.name": "Focus Time",
    "perk.focus_time.desc": "After every right answer, the zombies slow to a third of their speed for {a} seconds.",
    "perk.combo_shield.name": "Combo Shield",
    "perk.combo_shield.desc": "One wrong answer doesn't break your combo. The shield comes back after {a} more right answers.",
    "perk.word_bounty.name": "Big Word Bounty",
    "perk.word_bounty.desc": "Hard words (8+ letters, or ones you've missed before) pay {a}% more money.",
    "perk.extra_time.name": "Extra Time",
    "perk.extra_time.desc": "{a} more seconds to answer door, crate and trap questions, and the boss's questions.",
    "perk.perk_speed.name": "Fleet Foot",
    "perk.perk_speed.desc": "You move {a}% faster.",
    "perk.second_wind.name": "Second Wind",
    "perk.second_wind.desc": "Stamina comes back twice as fast, and after running dry you can sprint again at 10% instead of 20%.",
    "perk.pack_mule.name": "Pack Mule",
    "perk.pack_mule.desc": "Heavy guns slow you down and tire you out only half as much.",
    "perk.adrenaline.name": "Adrenaline",
    "perk.adrenaline.desc": "Every kill gives you {a}% extra speed for 3 seconds.",
    "perk.quick_hands.name": "Quick Hands",
    "perk.quick_hands.desc": "You reload and switch weapons {a}% faster.",
    "perk.piercing_rounds.name": "Piercing Rounds",
    "perk.piercing_rounds.desc1": "Every bullet carries on through one more zombie.",
    "perk.piercing_rounds.desc2": "Every bullet carries on through two more zombies.",
    "perk.last_round.name": "Last Round",
    "perk.last_round.desc1": "The last round in every magazine does triple damage.",
    "perk.last_round.desc2": "The last two rounds in every magazine do triple damage.",
    "perk.marksman.name": "Marksman",
    "perk.marksman.desc": "Fully aimed shots do {a}% more damage, and shotgun spread is halved.",
    "perk.bloodthirst.name": "Bloodthirst",
    "perk.bloodthirst.desc": "Every kill heals {a} HP, and a kill with the right word heals {b}.",
    "perk.perk_armor.name": "Riot Gear",
    "perk.perk_armor.desc": "You take {a}% less damage from bites and traps.",
    "perk.second_life.name": "Second Life",
    "perk.second_life.desc": "Once per wave, a hit that would kill you leaves you on {a}% health and knocks nearby zombies back.",
    "perk.thorns.name": "Thorns",
    "perk.thorns.desc": "A zombie that bites you takes {a} damage and is thrown back (never a kill, so it can't cost you an answer).",
    "perk.extra_slot.name": "Extra Weapon Slot",
    "perk.extra_slot.desc1": "Carry one more gun: 5 in all, plus the knife.",
    "perk.extra_slot.desc2": "Carry two more guns: 6 in all, plus the knife.",
    "perk.interest.name": "Savings Account",
    "perk.interest.desc": "Each time the shop opens you earn {a}% of the money you walk in with (up to ${b}).",
    "perk.lucky_charm.name": "Lucky Charm",
    "perk.lucky_charm.desc1": "Weapon crates roll their rarity twice and keep the better result.",
    "perk.lucky_charm.desc2": "Weapon crates roll their rarity three times and keep the best result.",

    // ---- Inventory Full (js/loadout.js) ----
    "inv.title": "Inventory Full",
    "inv.sub": "Choose a gun to swap out, or keep your loadout.",
    "inv.newGun": "NEW GUN",
    "inv.damage": "Damage",
    "inv.rate": "Fire rate",
    "inv.mag": "Magazine",
    "inv.weight": "Weight",
    "inv.held": "in hand",
    "inv.ammo": "Ammo {m} / {r}",
    "inv.replace": "Swap for the new gun",
    "inv.keep": "Keep Current Loadout",
    "inv.dropNote": "A gun you swap out is dropped at your feet — you have {s} seconds to pick it back up.",
    "inv.keepWall": "Keeping your loadout costs nothing.",
    "inv.keepBox": "If you keep your loadout, the new gun waits on the floor beside the box.",
    "inv.keepFloor": "If you keep your loadout, the new gun stays on the floor for later.",
    "inv.keepStays": "If you keep your loadout, it stays where it is.",

    // ---- Custom Vocabulary (js/customvocab.js) ----
    "cv.title": "Custom Vocabulary",
    "cv.intro": "Add your own words to a level. They join that level's word list the next time you start it, and they're kept in your save (Export Save included).",
    "cv.en": "English Word",
    "cv.th": "Thai Meaning",
    "cv.level": "Level",
    "cv.add": "Add Word",
    "cv.saveChanges": "Save Changes",
    "cv.cancel": "Cancel",
    "cv.import": "Import CSV…",
    "cv.edit": "Edit",
    "cv.delete": "Delete",
    "cv.confirmDelete": "Tap again to delete",
    "cv.empty": "No words added to {level} yet.",
    "cv.editing": "Editing “{w}” — change it and save, or cancel.",
    "cv.added": "Added “{w}” to {level}.",
    "cv.updated": "Saved “{w}” in {level}.",
    "cv.deleted": "Deleted “{w}”.",
    "cv.warnSame": "Heads-up: {others} has exactly the same Thai meaning in this level, so the two will never be on the field at the same time.",
    "cv.errEmpty": "Fill in both the English word and the Thai meaning.",
    "cv.errLong": "That's too long (32 letters for the English word, 80 characters for the meaning).",
    "cv.errLetters": "The English word can only use the letters A–Z (a hyphen, an apostrophe or a single space between words is fine).",
    "cv.errThai": "The meaning needs to be written in Thai.",
    "cv.errDup": "“{w}” is already in the game — it's one of the words in {level}. Nothing was saved.",
    "cv.errDupCustom": "“{w}” is already on your list for {level}. Nothing was saved.",
    "cv.errLevel": "Choose a level.",

    // ---- crate and mystery box ----
    "crate.ok": "OK",
    "crate.stats": "Damage: {d}<br>Fire rate: {r} rounds/s<br>Magazine: {m}<br>",
    "mystery.pick": "Pick 1 card",
    "mystery.pickSub": "One of them is a top-tier gun — try your luck",
    "mystery.take": "Take Gun",
    "mystery.reveal": "All cards revealed",
    "mystery.revealSub": "See what you missed",
    "mystery.yourPick": "← your pick",
    "mystery.dps": "DPS ~{n}",
    "mystery.elite": "  ★ ELITE",

    // ---- pause ----
    "pause.title": "Paused",
    "pause.resume": "Resume",
    "pause.tutorial": "Restart Tutorial",
    "pause.perks": "Perks",
    "pause.noPerks": "No perks yet — the shop sells four new ones between every wave.",
    "pause.perkHint": "Point at, tap or select a perk to see what it does.",

    // ---- tutorial ----
    "tut.move.title": "Move and look",
    "tut.move.desk": "Walk with W A S D · move the mouse to look · Shift to sprint · Space to jump",
    "tut.move.touch": "Drag the joystick (bottom left) to walk · drag on the right half of the screen to look · \"RUN\" to sprint",
    "tut.rule.title": "The main rule",
    "tut.rule.desk": "Read the Thai meaning at the top, then shoot the zombie carrying the matching English word — the wrong word costs health and speeds the zombies up",
    "tut.rule.touch": "Read the Thai meaning at the top, then shoot the zombie carrying the matching English word — the wrong word costs health and speeds the zombies up",
    "tut.shoot.title": "Shooting",
    "tut.shoot.desk": "Left click to shoot · hold right click to aim · R to reload · 1-5 to switch weapons · V to hear the word again",
    "tut.shoot.touch": "FIRE to shoot · AIM to zoom · R to reload · the number row switches weapons · 🔊 hears the word",
    "tut.door.title": "Doors",
    "tut.door.desk": "Press E to open or close a door — a closed door holds zombies back for a while",
    "tut.door.touch": "Press E to open or close a door — a closed door holds zombies back for a while",
    "tut.pickup.title": "Items",
    "tut.pickup.desk": "Walk over items to pick them up: money, ammo, health and weapon crates",
    "tut.pickup.touch": "Walk over items to pick them up: money, ammo, health and weapon crates",
    "tut.objectives.title": "Level goals",
    "tut.objectives.desk": "Surviving isn't enough — check \"Objectives x/6\" on the right, or press ESC for the full list (3 keys, rooms to explore, accuracy and the boss)",
    "tut.objectives.touch": "Surviving isn't enough — check \"Objectives x/6\" on the right, or press II for the full list (3 keys, rooms to explore, accuracy and the boss)",
    "tut.wallgun.title": "Wall guns",
    "tut.wallgun.desk": "Guns on the walls can be bought (press E when you have the money) — the heavier the gun, the slower you move and the faster you tire",
    "tut.wallgun.touch": "Guns on the walls can be bought (press E when you have the money) — the heavier the gun, the slower you move and the faster you tire",
    "tut.mystery.title": "Mystery box",
    "tut.mystery.desk": "$1,000 a try: pick 1 of 6 cards — one of them is always top tier",
    "tut.mystery.touch": "$1,000 a try: pick 1 of 6 cards — one of them is always top tier",
    "tut.shopTip": "The shop opens between waves: Full Health and Full Ammo are always on sale, and four perks change every wave — the clock is ticking",

    // ---- touch controls and layout editor ----
    "touch.fire": "FIRE", "touch.aim": "AIM", "touch.interact": "E", "touch.reload": "R", "touch.jump": "JUMP", "touch.sprint": "RUN", "touch.pause": "II",
    "touchcfg.title": "Customize Controls",
    "touchcfg.hide": "Hide",
    "touchcfg.show": "Show",
    "touchcfg.hint": "Drag a button to move it · tap a button once to select it, then resize it below",
    "touchcfg.selected": "Selected",
    "touchcfg.none": "— tap a button to select —",
    "touchcfg.size": "Button size",
    "touchcfg.small": "Small", "touchcfg.medium": "Medium", "touchcfg.large": "Large",
    "touchcfg.resetOne": "Reset this button",
    "touchcfg.opacity": "Button opacity",
    "touchcfg.sens": "Look drag sensitivity",
    "touchcfg.resetAll": "Reset All",
    "touchcfg.done": "Done",
    "touchcfg.confirmReset": "Reset every position, size, opacity and sensitivity to default?",
    "touchcfg.joystick": "Move stick", "touchcfg.fire": "Fire button (FIRE)", "touchcfg.ads": "Aim button", "touchcfg.interact": "Use button (E)",
    "touchcfg.reload": "Reload button (R)", "touchcfg.jump": "Jump button", "touchcfg.sprint": "Run button", "touchcfg.pause": "Pause button",
    "touchcfg.slots": "Weapon row",

    // ---- signs and posters in the world ----
    "world.wallWeight": "Weight: {w}",
    "world.info": "Information",
    "world.schoolName": "BAN NONG SCHOOL",
    "world.welcome": "Welcome",
    "world.banner1": "WIN", "world.banner2": "GO TEAM", "world.banner3": "OUR TEAM",
    "world.home": "HOME", "world.away": "AWAY",
    "world.emergency": "Emergency Dept.",
    "world.emergencySub": "THIS WAY  →",
    "world.triage": "TRIAGE",
    "world.blastDoor": "Blast Door",
    "world.sealed": "SEALED",
    "world.reactor": "Reactor Room",
    "world.coreUnstable": "CORE  UNSTABLE",
    "poster.noRunning": "NO RUNNING",
    "poster.numbers": "1 2 3",
    "poster.abc": "ABC",
    "poster.worldMap": "WORLD MAP",
    "poster.clean": "KEEP IT CLEAN",
    "poster.periodic": "PERIODIC TABLE",
    "poster.exams": "EXAM WEEK!",
    "poster.greens": "EAT YOUR GREENS",
    "notice.1": "NOTICE", "notice.2": "NO CLASS", "notice.3": "SPORTS DAY", "notice.4": "MIDTERMS", "notice.5": "LOST CAT", "notice.6": "CLUBS",
    "sign.extinguisher": "FIRE EXTINGUISHER",
    // round 3: story notes and the Notes Journal
    "menu.journal": "Notes Journal",
    "journal.title": "Notes Journal",
    "journal.found": "Notes found: {n} / {total}",
    "journal.none": "No story notes found here yet.",
    "journal.soon": "The story notes for this level are coming in a later update.",
    "journal.notFound": "Not found yet",
    "notes.keep": "Keep Note",
    "notes.close": "Close",
    "notes.listen": "Listen",
    "notes.stop": "Stop",
    "notes.cefrAria": "CEFR level {level}",
    "notes.kept": "Note kept",
    "notes.keptAgain": "Note kept (already in your journal)",
    "notes.keptText": "Notes Journal: {n} / {total}",
    "prompt.note": "Press {key} to read",
    // round 3: the third floor and its rewards
    "prompt.gate3": "3rd floor locked · Notes read {n}/{nn} · Correct words {c}/{cc}",
    "prompt.gate3Second": " · Open the 2nd floor first",
    "banner.gate3Locked": "Locked",
    "banner.thirdFloor": "3rd floor unlocked!",
    "banner.thirdFloorText": "The grille on the stairs has lifted",
    "prompt.safe": "Press {key} to open the principal's safe", "prompt.safeUsed": "Empty",
    "prompt.trophy": "Press {key} to search the trophy case", "prompt.trophyUsed": "Empty",
    "prompt.coffee": "Press {key} to make a coffee", "prompt.coffeeUsed": "Out of coffee",
    "prompt.radio": "Press {key} to use the radio", "prompt.radioUsed": "The battery is flat",
    "banner.trophy": "Sports Day prize money",
    "banner.trophyText": "+${n}",
    "banner.coffee": "Fresh coffee",
    "banner.coffeeText": "Free perk: {perk} (level {lvl})",
    "banner.coffeeNone": "You already have every perk at its highest level.",
    "banner.radio": "The radio crackles",
    "banner.radioText": "Notes still lying about are marked on your map ({n}).",
    // round 3: the minimap
    "map.north": "N",
    "map.aria": "Minimap",
    // round 3: the campus
    "world.rescueUnit": "DISTRICT RESCUE UNIT",
    "world.checkpoint": "CHECKPOINT",
    "world.checkpointSub": "Evacuation point · Wait here",
    "world.schoolBus": "SCHOOL BUS",
    "world.sportsHall": "SPORTS HALL",
    // round 3: the name over every door (G2)
    "room.classroom": "Classroom", "room.library": "Library", "room.meeting": "Meeting Room", "room.boardroom": "Board Room",
    "room.science": "Science Lab", "room.chemistry": "Chemistry Lab", "room.physics": "Physics Lab",
    "room.music": "Music Room", "room.art": "Art Room", "room.nurse": "Nurse's Office",
    "room.computer": "Computer Room", "room.languageLab": "Language Lab", "room.principal": "Principal's Office",
    "room.canteen": "Canteen", "room.toilets": "Toilets", "room.office": "School Office", "room.deputy": "Deputy Head",
    "room.staffoffice": "Staff Office", "room.detention": "Detention Room", "room.storeroom": "Storeroom",
    "room.changing": "Changing Room", "room.sports": "PE Store", "room.staff": "Staff Room", "room.lounge": "Staff Lounge",
    "room.archive": "Archive", "room.trophy": "Trophy Room", "room.broadcast": "Broadcast Room", "room.stairs": "Stairs to 3rd Floor",
    // round 3: what is written on the boards (lines split at |)
    "board.pastSimple": "Past simple: go - went, see - saw|Yesterday I ____ to the market.",
    "board.vocab": "New words:|abandon, reluctant, inevitable|evacuate, resilient, vivid",
    "board.homework": "Homework: page 42, exercises 3-5|Hand in on Friday!",
    "board.timetable": "EXAM WEEK|Mon: English   Tue: Maths|Wed: Science   Thu: Thai",
    "board.menu": "TODAY'S MENU|Rice soup · Fried chicken|Fresh fruit",
    "board.silence": "SILENCE",
    "board.onAir": "ON AIR",
    "board.groups": "Stay with your group.|Do NOT go outside.|Wait for a teacher.",
    "board.time": "3:17",
    "board.evacuate": "EVACUATION ROUTE|Meet at the football field",
    "board.library": "SILENCE PLEASE|Return all books by Friday",
    "board.physics": "Physics: F = m x a|Newton's laws of motion",
    "board.chemistry": "Chemistry: H2O, NaCl, CO2|Always wear your goggles!",
    "board.music": "Year 8 Choir|Practice: Thursday, 3 pm",
    "board.wellDone": "Well done, Year 9!|Sports Day Champions",
    "board.blank": " ",
    // round 3: places on the campus (the explore objective, the minimap)
    "place.FIELD": "Football Field", "place.GARDEN": "Flower Garden", "place.SALA_FRONT": "Front Sala",
    "place.SALA_FIELD": "Field Sala", "place.SALA_GARDEN": "Garden Sala", "place.CARPARK": "Car Park",
    "place.CHECKPOINT": "Rescue Checkpoint", "place.BACKYARD": "Service Yard",
    // round 4: the lobby
    "lobby.tab.campaign": "CAMPAIGN",
    "lobby.tab.training": "TRAINING & CUSTOM",
    "lobby.featured": "FEATURED",
    "lobby.icon.settings": "Settings", "lobby.icon.leaderboard": "Leaderboard", "lobby.icon.achievements": "Achievements",
    "lobby.icon.armory": "Weapon Log", "lobby.icon.wordlog": "Vocabulary Log", "lobby.icon.journal": "Notes Journal", "lobby.icon.help": "How to Play",
    "lobby.mode.endless": "Endless Mode", "lobby.mode.daily": "Daily Challenge", "lobby.mode.practice": "Practice Mode", "lobby.mode.custom": "Custom Vocabulary",
    "lobby.badge.featured": "FEATURED", "lobby.badge.campaign": "CAMPAIGN", "lobby.badge.survival": "SURVIVAL", "lobby.badge.daily": "DAILY EVENT",
    "lobby.badge.training": "TRAINING", "lobby.badge.creative": "CREATIVE", "lobby.badge.locked": "LOCKED",
    "lobby.desc.school": "The bell rang at 3:17 and nobody went home. Search three floors and a whole campus, read what the survivors left behind, and fight your way to the rescue point.",
    "lobby.desc.hospital": "The lights still hum in the empty wards. Every door hides a patient who did not leave — and a word you need to know.",
    "lobby.desc.bunker": "Deep under the city, the last shelter has gone quiet. Only the hardest words will open the blast doors.",
    "lobby.desc.endless": "No exit, no last wave. Every word from every level, faster and faster, for as long as you can last.",
    "lobby.desc.daily": "One set of words and one seed for everyone today. One try counts for your best score — a new challenge at midnight.",
    "lobby.desc.practice": "No zombies, no clock. Go over the words you miss most, with meanings and pronunciation.",
    "lobby.desc.custom": "Add your own words to any level, or import a whole list, and the zombies will carry them.",
    "lobby.unlock.hospital": "Clear the Abandoned School to unlock",
    "lobby.unlock.bunker": "Clear the Abandoned Hospital to unlock",
    "lobby.lockedShort": "Locked",
    "lobby.best": "High score", "lobby.bestWave": "Best wave", "lobby.notes": "Notes", "lobby.words": "Words mastered",
    "lobby.guns": "Guns found", "lobby.today": "Today's best", "lobby.next": "Next challenge", "lobby.weak": "Words to review",
    "lobby.yourWords": "Your words", "lobby.sets": "Imported lists",
    "lobby.waves": "{n} waves",
    "lobby.meta.endless": "All levels · No end",
    "lobby.meta.practice": "No zombies · Your pace",
    "lobby.meta.custom": "Your words · Any level",
    "lobby.play": "Play",
    "lobby.open": "Open",
    "lobby.tapAgain": "Tap again to",
    "lobby.hint.kb": "<kbd>←</kbd><kbd>→</kbd> Choose · <kbd>Enter</kbd> Select · <kbd>Q</kbd><kbd>E</kbd> Switch tab · <kbd>↑</kbd> Menu",
    "lobby.hint.pad": "<kbd>D-pad</kbd> Choose · <kbd class=\"pad-a\">A</kbd> Select · <kbd>LB</kbd><kbd>RB</kbd> Switch tab · <kbd>↑</kbd> Menu",
    "lobby.hint.touch": "Swipe to choose · Tap the card again to play · Tap a tab to switch",
    "howto.tutorial": "Replay Tutorial",
    "howto.import": "Import Vocabulary",

    // ---- weapon names ----
    "weapon.melee": "Combat Knife",
    "weapon.pistol": "Pistol", "weapon.shotgun": "Shotgun", "weapon.smg": "SMG", "weapon.rifle": "Assault Rifle", "weapon.lmg": "LMG",
    "weapon.sniper": "Sniper", "weapon.railgun": "Piercing Railgun", "weapon.grenadelauncher": "Grenade Launcher",
    "weapon.golden_smg": "Golden Vocabulary SMG", "weapon.school_wall": "Faculty Enforcer", "weapon.hospital_wall": "Trauma Cannon",
    "weapon.bunker_wall": "Vault Breaker", "weapon.hall_monitor": "Hallway Monitor", "weapon.detention_slug": "Detention Slugger",
    "weapon.pop_quiz": "Pop Quiz", "weapon.cafeteria_cleaver": "Cafeteria Cleaver", "weapon.honor_roll": "Honor Roll",
    "weapon.science_fair": "Science Fair", "weapon.art_attack": "Art Attack", "weapon.principals_verdict": "Principal's Verdict",
    "weapon.scrap_spitter": "Scrap Spitter", "weapon.nail_driver": "Nail Driver", "weapon.hall_sweeper": "Hall Sweeper",
    "weapon.chalk_burster": "Chalk Burster", "weapon.detention_deuce": "Detention Deuce", "weapon.rust_repeater": "Rust Repeater",
    "weapon.gym_grinder": "Gym Class Grinder", "weapon.copper_coil": "Copper Coil", "weapon.locker_lancer": "Locker Lancer",
    "weapon.bus_bulldog": "Bus Stop Bulldog", "weapon.thunder_chalk": "Thunder Chalk", "weapon.void_principal": "Void Principal",
    "weapon.prism_lance": "Prism Lance", "weapon.final_bell": "Final Bell", "weapon.meteor_detention": "Meteor Detention",
    "weapon.sterile_slug": "Sterile Slug", "weapon.rebound_pistol": "Rebound Pistol", "weapon.scalpel_smg": "Scalpel SMG",
    "weapon.triage_carbine": "Triage Carbine", "weapon.crash_cart": "Crash Cart", "weapon.iv_repeater": "IV Repeater",
    "weapon.bone_saw": "Bone Saw", "weapon.morphine_mist": "Morphine Mist", "weapon.quarantine_lance": "Quarantine Lance",
    "weapon.autoclave": "Autoclave", "weapon.defib_driver": "Defib Driver", "weapon.vital_sign": "Vital Sign",
    "weapon.code_blue": "Code Blue", "weapon.gauze_gun": "Gauze Gun", "weapon.syringe_spitter": "Syringe Spitter",
    "weapon.plaster_popper": "Plaster Popper", "weapon.oxygen_burst": "Oxygen Burst", "weapon.reflex_hammer": "Reflex Hammer",
    "weapon.dialysis_drum": "Dialysis Drum", "weapon.x_ray_beam": "X-Ray Beam", "weapon.anesthetic_arc": "Anesthetic Arc",
    "weapon.cardiac_coil": "Cardiac Coil", "weapon.plague_thrower": "Plague Thrower", "weapon.gene_splicer": "Gene Splicer",
    "weapon.flatline": "Flatline", "weapon.rebar_repeater": "Rebar Repeater", "weapon.breach_gauge": "Breach Gauge",
    "weapon.scrap_auto": "Scrap Auto", "weapon.service_rifle": "Service Rifle", "weapon.pipe_mortar": "Pipe Mortar",
    "weapon.vent_ripper": "Vent Ripper", "weapon.bolt_thrower": "Bolt Thrower", "weapon.siege_slug": "Siege Slug",
    "weapon.drum_hammer": "Drum Hammer", "weapon.capacitor_lance": "Capacitor Lance", "weapon.thermite_tube": "Thermite Tube",
    "weapon.overwatch": "Overwatch", "weapon.warhead": "Warhead", "weapon.nut_cracker": "Nut Cracker",
    "weapon.chain_feeder": "Chain Feeder", "weapon.blast_door": "Blast Door", "weapon.tri_burst": "Tri-Burst",
    "weapon.sledge_shot": "Sledge Shot", "weapon.rail_spike": "Rail Spike", "weapon.arc_welder": "Arc Welder",
    "weapon.mag_driver": "Mag Driver", "weapon.mortar_pup": "Mortar Pup", "weapon.reactor_core": "Reactor Core",
    "weapon.last_stand": "Last Stand", "weapon.doomsday": "Doomsday",
  },
};

G.T = function (key, vars) {
  const table = G.STRINGS[G.lang] || G.STRINGS.en;
  let s = table[key];
  if (s == null) s = G.STRINGS.en[key];
  if (s == null) { if (!G._missingKeys) G._missingKeys = {}; G._missingKeys[key] = true; return key; }
  if (vars) s = s.replace(/\{(\w+)\}/g, (m, k) => (vars[k] != null ? vars[k] : m));
  return s;
};

// fill the static page: data-i18n (text), data-i18n-html, data-i18n-aria
G.applyStaticStrings = function (root) {
  root = root || document;
  root.querySelectorAll("[data-i18n]").forEach((el) => { el.textContent = G.T(el.getAttribute("data-i18n")); });
  root.querySelectorAll("[data-i18n-html]").forEach((el) => { el.innerHTML = G.T(el.getAttribute("data-i18n-html")); });
  root.querySelectorAll("[data-i18n-aria]").forEach((el) => { el.setAttribute("aria-label", G.T(el.getAttribute("data-i18n-aria"))); });
  document.documentElement.lang = G.lang;
};

// names and labels carried on game data, set from the table by id
G.localizeData = function () {
  (G.LEVELS || []).forEach((l) => { l.name = G.T("level." + l.id); });
  if (G.WEAPON_DEFS) Object.values(G.WEAPON_DEFS).forEach((d) => { d.name = G.T("weapon." + d.id); });
  if (G.MELEE_DEF) G.MELEE_DEF.name = G.T("weapon.melee");
  (G.ACHIEVEMENTS || []).forEach((a) => { a.name = G.T("ach." + a.id + ".name"); a.desc = G.T("ach." + a.id + ".desc"); });
  (G.SHOP_ITEMS || []).forEach((it) => { it.label = G.T("shopItem." + it.id); });
  if (G.RARITY) Object.values(G.RARITY).forEach((r) => { r.label = G.T("rarity." + r.key); });
  (G.WEIGHT_CLASSES || []).forEach((w) => { w.label = G.T("weight." + w.key); });
};

// Signs and posters are drawn on fixed-size canvases, and a translation can be
// longer than the text they were laid out for: shrink the font until it fits.
G.fitFont = function (ctx, text, px, maxW, family) {
  const f = (p) => `bold ${p}px ${family || "sans-serif"}`;
  ctx.font = f(px);
  while (px > 10 && ctx.measureText(text).width > maxW) ctx.font = f(--px);
  return px;
};

// before G.Game.init (registered earlier, so it runs first)
window.addEventListener("DOMContentLoaded", () => { G.localizeData(); G.applyStaticStrings(); });
